### ISSUE TITLE
Ability to specify a collection name to an entity class

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#1]
It would be very useful to be able to specify a different collection name to an entity class thru attributes, i.e.

`
[collection(name="system_useraccount")]
public class SystemUserAccount { ... }
`

**Comment by dj-nitehawk** [comment]
thanks for the suggestion. i will look in to it...

**Comment by paolobriones** [comment]
Thank you, awesome work!

**Comment by paolobriones** [comment]
Hi DJ NightHawk, please see my PR that adds support for specifying a different collection name to an entity class. Thanks!

**Comment by paolobriones** [comment]
@dj-nitehawk if you add [collection(Name="")] to an entity class, it will use that name when saving to mongodb, also, if you do not add that attribute to the entity class, it will use the name of the entity class when saving to mongodb. I wanted to update the wiki, but not able to do so

**Comment by dj-nitehawk** [comment]
@paolobriones pr has been merged to dev branch. will release the changes with the next version later today. btw, i refactored the attribute to be used as follows:
```csharp
    [Name("Writer")]
    public class Author : Entity
    {
        ...
    }
```
i will update the wiki as well...
thanks a lot for your contribution.
