### ISSUE TITLE
support for multiple database?

### ISSUE THREAD

**Issue by gshockim** [dj-nitehawk/MongoDB.Entities#10]
It looks use only one static db so looks support only one database.

**Comment by dj-nitehawk** [comment]
sorry it cannot be done with the current architecture of the library. it would break the API completely if i add multiple database support.

**Comment by gshockim** [comment]
PSA who anybody want multiple db support.
I made a crappy one that support multiple db support
https://github.com/gshockim/Replica.MongoDB.Entities

**Comment by dj-nitehawk** [comment]
cool... i will have look at it too... thanks!
