### ISSUE TITLE
How to add new entity in parent entity on update time?

### ISSUE THREAD

**Issue by kingsanu-production** [dj-nitehawk/MongoDB.Entities#101]
I have jobs and once candiadte apply for job his id insert into jobs.applied. how can i do it plz help me.

**Comment by dj-nitehawk** [comment]
can you show me your simplified class definitions for job and candidate? and what kind of relationship you want? embedded or referenced?

**Comment by dj-nitehawk** [comment]
here's a many-to-many relationship example:
```csharp
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestApplication
{
    public class JobListing : Entity
    {
        public string Title { get; set; }

        [OwnerSide]
        public Many<Candidate> Applicants { get; set; }

        public JobListing()
            => this.InitManyToMany(() => Applicants, c => c.AppliedJobs);
    }

    public class Candidate : Entity
    {
        public string FullName { get; set; }

        [InverseSide]
        public Many<JobListing> AppliedJobs { get; set; }

        public Candidate()
            => this.InitManyToMany(() => AppliedJobs, j => j.Applicants);
    }

    public static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("test");

            var job = new JobListing { Title = ".net core backend engineer" };
            await job.SaveAsync();

            var candidate = new Candidate { FullName = "donald duck" };
            await candidate.SaveAsync();

            await candidate.AppliedJobs.AddAsync(job);
            await job.Applicants.AddAsync(candidate);
        }
    }
}
```

**Comment by kingsanu-production** [comment]
![image](https://user-images.githubusercontent.com/65809324/107181930-d5d5c400-6a01-11eb-8556-db7a15c5f9bb.png)

See line 3 say without candidate one record save, appliedjob not allowed to add new record. so one candidate will not create his self again and again. It clearly give error to do not add new appliedjob till you do not create one record of candidate and take reference of candidate to add new applied job.

So let me tell you what i would, in one document job's appliedjob field containt reference of all candidate who applied a job. next time some another user click to apply so without Find<T> whole record or something new entry of candidate ID add to appliedjob field.

**Comment by dj-nitehawk** [comment]
you can do either of these:
```csharp
await DB.Entity<Candidate>("xxxxxxxxxxxxxxxxxx")
        .AppliedJobs
        .AddAsync(job);

await new Candidate { ID = "xxxxxxxxxxxxxxxxxx" }
            .AppliedJobs
            .AddAsync("yyyyyyyyyyyyyyyy");
```
so you need to know the `ID` of the parent that you want to add a child to. and there's no need to retrieve the parent first.

hope that answers your problem...

**Comment by kingsanu-production** [comment]
OMG! you are amazing and like to be your member.
Thanks

**Comment by kingsanu-production** [comment]
`public class Jobs : Entity
        {
            public string Title { get; set; }
            public Many<Candidate> AppliedCandidates { get; set; }
            public Jobs()
            {
                this.InitOneToMany(() => AppliedCandidates);
            }
        }

        public class Candidate : Entity
        {
            public string Firstname { get; set; }
        }

            var job = await new Jobs { Title = "Sr. Project Manager" }.SaveAsync();
            var candidate = await new Candidate { Firstname = "Dj-nitehawk" }.SaveAsync();

            await DB.Entity<Jobs>(job.UpsertedId.ToString())
                .AppliedCandidates.AddAsync(candidate.UpsertedId.ToString());
`
You can see here, i use one to many relationship but database not updated with nothing.
![image](https://user-images.githubusercontent.com/65809324/107200113-4807d200-6a1d-11eb-9009-7aa1afc16078.png)

**Comment by kingsanu-production** [comment]
So is it will support pagination of appliedcandidate of job?

**Comment by dj-nitehawk** [comment]
easiest way to paginate would be the following:
```csharp
await DB.Entity<Candidate>("xxxxxxxxxxxxxxxxxx")
        .AppliedJobs
        .ChildrenQueryable()
        .Skip(10)
        .Take(50)
        .ToListAsync();
```

**Comment by kingsanu-production** [comment]
![image](https://user-images.githubusercontent.com/65809324/107224668-bd839a80-6a3d-11eb-981d-5c5f9cfa8d46.png)

why i can't able to access Title?

**Comment by dj-nitehawk** [comment]
i'm assuming you want to retrieve all records with combined info from both collections right? then try this:
```csharp
var result = await DB.Entity<JobListing>()
    .Applicants.JoinQueryable() //join collection
    .Join(
        DB.Queryable<JobListing>(), //foreign collection
        jr => jr.ParentID,          //local field
        jl => jl.ID,                //foreign field
        (jr, jl) => new { jl.Title, cID = jr.ChildID }) //projection
    .Join(
        DB.Queryable<Candidate>(), //foreign collection
        x => x.cID,                //local field
        c => c.ID,                 //foreign field
        (x, c) => new { x.Title, c.FullName }) //projection
    .ToListAsync();
```
if not, let me know your specific requirement.

and the library will remain forever free and open source. you can however [donate a few bucks](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=9LM2APQXVA9VE) to cause if you like ;-)

**Comment by dj-nitehawk** [comment]
here's another shorter way. here you start with the candidate collection:
```csharp

    public class JobListing : Entity
    {
        public string Title { get; set; }
        public Many<Candidate> Applicants { get; set; }

        public JobListing()
            => this.InitOneToMany(() => Applicants);
    }

    public class Candidate : Entity
    {
        public string FullName { get; set; }
        public One<JobListing> Job { get; set; }
    }

            var job = new JobListing { Title = ".net core backend engineer" };
            await job.SaveAsync();

            var candidate = new Candidate { FullName = "donald duck", Job = job };
            await candidate.SaveAsync();

            await job.Applicants.AddAsync(candidate);

            var result = await DB
                .Queryable<Candidate>()
                .Join(
                    DB.Queryable<JobListing>(),
                    c => c.Job.ID,
                    jl => jl.ID,
                    (c, jl) => new { jl.Title, c.FullName })
                .ToListAsync();
```

**Comment by kingsanu-production** [comment]
Thanks Mr. DJ-nitehawk.
As your first comment i tried it work well, but not will second comment, which is nice and shorter to use.

public class Jobs : Entity
        {
            public string Title { get; set; }
            public Many<Candidate> AppliedCandidates { get; set; }
            public Jobs()
            {
                this.InitOneToMany(() => AppliedCandidates);
            }
        }

        public class Candidate : Entity
        {
            public string Firstname { get; set; }
            public One<Jobs> job { get; set; }
        }

var jobfirst = DB
                .Queryable<Jobs>()
                .Join(
                    DB.Queryable<Candidate>(),
                    c => c.ID,
                    jl => jl.job.ID,
                    (c, jl) => new { jl.Firstname, c.Title })
                .ToList();

            //output 0

            var candidatefirst = DB
                .Queryable<Candidate>()
                .Join(
                    DB.Queryable<Jobs>(),
                    c => c.job.ID,
                    jl => jl.ID,
                    (c, jl) => new { jl.Title, c.Firstname })
                .ToList();

            //output 0

**Comment by dj-nitehawk** [comment]
works for me... i think you forgot the step circled in red below:
![screen](https://user-images.githubusercontent.com/7043768/107317622-003a8680-6ac1-11eb-9a45-c2ee793152b2.png)
