### ISSUE TITLE
Dynamic Aggregation stages using string template

### ISSUE THREAD

**Issue by susahin80** [dj-nitehawk/MongoDB.Entities#103]
Related with the  [issue 102](https://github.com/dj-nitehawk/MongoDB.Entities/issues/102) I wanted to add [facet ](https://docs.mongodb.com/manual/reference/operator/aggregation/facet/) aggregation. 

This time I used string templates. ( if it is possible to add facet to the answer in issue 102, it would also help, but anyway I chose string templates this time).

I could dynamically constructed the string template like this, and it worked, but it is dirty:)
Do you think this kind of solution is good? Any suggestions?

If the pipeline method would accept input of an array (array of stages), this kind of dynamic (optional) aggregations would be easier? Would you consider adding this feature?

```csharp
        [HttpGet("search-facet")]
        public async Task<IActionResult> SearchAndFacet(FilterProductDTO dto)
        {

            int page = dto.Page.HasValue ? dto.Page.Value : 1;
            int pageSize = dto.PageSize.HasValue ? dto.PageSize.Value : 10;
            int skip = (page - 1) * pageSize;

            var stages = new List<string>();

            if (!string.IsNullOrEmpty(dto.SearchTerm))
            {
                stages.Add(@"{$match: {
	                      $text: { $search: '<search_term>' }
	                    }}".Replace("<search_term>", dto.SearchTerm));

                stages.Add(@" {$sort: {
	                      score: { $meta: 'textScore' }
	                    }}");
            }

            if (!string.IsNullOrEmpty(dto.CategoryId))
            {
                stages.Add(@" {
                '$match': {
                  'Category': new ObjectId('<category_id>')
                }
              }".Replace("<category_id>", dto.CategoryId));
            }

            if (dto.MinPrice.HasValue)
            {
                stages.Add(@" {
                '$match': {
                  'Price': { $gte: <min_price> }
                }
              }".Replace("<min_price>", dto.MinPrice.Value.ToString(new NumberFormatInfo() { NumberDecimalSeparator = "."})));
            }

            if (dto.MaxPrice.HasValue)
            {
                stages.Add(@" {
                '$match': {
                  'Price': { $lte: <max_price> }
                }
              }".Replace("<max_price>", dto.MaxPrice.Value.ToString(new NumberFormatInfo() { NumberDecimalSeparator = "." })));
            }

            stages.Add(@"{$facet: {
		                      TotalRecords: [
			                    {
			                      $count: 'total'
			                    }
		                      ],
		                      Products: [
			                    {
			                      $skip: <skip>
			                    },
			                    {
			                      $limit: <limit>
			                    }
		                      ]
	                    }}"); //.Replace("<skip>", skip.ToString()).Replace("<limit>", pageSize.ToString()));

            stages.Add(@"{$addFields: {
	                      TotalRecords: {
		                    $arrayElemAt: [ '$TotalRecords.total', 0]
	                      }
	                    }}");

            var template = $"[{string.Join(',', stages)}]";

            var pipeline = new Template<ProductEntity, ProductSearchResultDTO>(template)
                    .Tag("skip", skip.ToString())
                    .Tag("limit", pageSize.ToString());

            var products = await DB.PipelineAsync(pipeline);

            return Ok(products);

        }
```

**Comment by dj-nitehawk** [comment]
shouldn't be too difficult...
let me have a look...

**Comment by susahin80** [comment]
It would be also nice to not to have to use tag methods, it looks like it is required, it would be good to if it was optional, because I want to be able to the replacement of parameters myself.

**Comment by dj-nitehawk** [comment]
just released a [beta version](https://www.nuget.org/packages/MongoDB.Entities/20.10.0-beta1) with support for dynamic building of stages with templates.

use the `.AppendStage()` method like so:

```csharp
var pipeline = new Template<Product, ProductSearchResultDTO>("[]"); //start with empty pipeline!

if (!string.IsNullOrEmpty(dto.SearchTerm))
    pipeline.AppendStage("{ $match: { $text: { $search: '<search_term>' } } }");

if (dto.MinPrice.HasValue)
    pipeline.AppendStage("{ $match: { <Price>: { $gte: <min_price> } } }");

pipeline.AppendStage(@"
{
    $facet: {
        <TotalRecords>: [
            {
                $count: 'total'
            }
        ],
        <Products>: [
            {
                $skip: <skip>
            },
            {
                $limit: <limit>
            }

        ]
    }
}");

pipeline.AppendStage(@"
{
    $set: {
        <TotalRecords>: { $first: '$TotalRecords.total' }
    }
}");

pipeline
.Tag("search_term", dto.SearchTerm)
.Tag("min_price", $"{dto.MinPrice}")
.Property(p => p.Price)
.PathsOfResult(r => new
{
    r.TotalRecords,
    r.Products
})
.Tag("skip", "0")
.Tag("limit", "2");

var result = await DB.PipelineAsync(pipeline);
```

**Comment by dj-nitehawk** [comment]
> It would be also nice to not to have to use tag methods, it looks like it is required, it would be good to if it was optional, because I want to be able to do the replacement of parameters myself, it is more flexible.

tag methods are not required now when you instantiate the template with an empty pipeline `"[]"`

give the new functionality a good test run. see if you can break it.

thanks for the idea!!!

**Comment by susahin80** [comment]
Great, I wil try

**Comment by susahin80** [comment]
I confirm that this works:) thank you.

Would be it possible to apply nodejs [mongoose ](https://mongoosejs.com/docs/api/aggregate.html#aggregate_Aggregate) style aggregation like the following? 

Input is an array type, not a string, and the stages are javascript objects.

  const result = await Bug.aggregate([
    {
      $match: {
        status: query.status,
      },
    },
    {
      $lookup: {
        from: "users",
        localField: query.localField,
        foreignField: "_id",
        as: "User",
      },
    },
    {
      $addFields: {
        User: {
          $arrayElemAt: ["$User", 0],
        },
      },
    },
    {
      $group: {
        _id: "$User.email",
        count: {
          $sum: 1,
        },
      },
    },
    {
      $sort: {
        count: -1,
      },
    },
  ]);

**Comment by dj-nitehawk** [comment]
you can use the official driver aggregate method like so:

`DB.Collection<Product>().AggregateAsync(...)`

but then you'll be dealing with the driver directly.

**Comment by susahin80** [comment]
ok thanks, AppendStage method is good enough :)
