### ISSUE TITLE
Ability to check if MongoDB server or specific database is available

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#104]
For maintenance features, we should be able to check if the server specified via the connection-string is valid or if the database exists.

This might be a useful feature, instead of relying on the API throwing an exception, we should be able to test the connection at app startup or on demand.

**Comment by dj-nitehawk** [comment]
check out the [latest beta](https://www.nuget.org/packages/MongoDB.Entities/20.12.0-beta1)
you can now do the following:
```csharp
bool isConnectable = await DB.Database("MyDatabase").IsAccessibleAsync();

bool dbExists = await DB.Database("MyDatabase").ExistsAsync();
```

the above can only be done once the connections have been initialized though.

to test the connection on startup, simply wrap the `DB.InitAsync` call in a try/catch block

**Comment by paolobriones** [comment]
Thanks! will try it today

**Comment by paolobriones** [comment]
Looks good!

```
await DB.InitAsync("admin", MongoClientSettings.FromConnectionString("mongodb://127.0.0.1:27017"));
bool isConnectable = await DB.Database("admin").IsAccessibleAsync();
bool dbExists = await DB.Database("admin").ExistsAsync();
```

**Comment by dj-nitehawk** [comment]
did you try interrupting connectivity with the server? (after connection has been initialized)

**Comment by paolobriones** [comment]
I just tried it out, i executed the same isConnectable and dbExists code and it works, once i stopped the mongodb container, isConnectable and dbExists returned false. 

I did notice that the call to ExistsAsync() takes longer than IsAccessibleAsync() when mongodb is no longer available.

**Comment by dj-nitehawk** [comment]
you can set the optional `timeout` parameter of those methods if you wanna reduce the default 5 seconds setting

**Comment by paolobriones** [comment]
looks good! thanks!
