### ISSUE TITLE
Ability to change the serialized property name

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#106]
We should have the ability to change the serialized property name when serializing and saving to mongodb; similar to the the way we are able to change the name of the class object. for example:

```cs
[Name("employee")]
public class EmployeeEntity : Entity {
     [Name("fname")]
     public string FirstName { get; set; }

     [Name("lname")]
     public string LastName { get; set; }
}
```
Should be serialized to:

```json
{ 
    "_id": {  "$oid": "60b36d297e3d155fe85a4b84" },
    "fname": "aaa",
    "lname": "bbb"
}
```
Or by default, when serializing to json, all properties are converted to lowercase

**Comment by dj-nitehawk** [comment]
there is `[BsonElement("fieldName")]` which is supplied by the driver

**Comment by paolobriones** [comment]
i was thinking to have a mongodb-entities specific attribute, similar to NameAttribute.
what do you think?

**Comment by dj-nitehawk** [comment]
yeah i could add an attribute called `[Field("FieldName")]`. sounds good?
because we can't use the same `[Name(...)]` attribute for both purposes.

**Comment by paolobriones** [comment]
i am so spoiled with how good the api does things, i would love these features to be all built in and without having to reach out into the official driver as much as possible :)

**Comment by dj-nitehawk** [comment]
yeah i totally understand where you're at ;-)
i'll add a new attribute.
are there any other attributes from the driver you use frequently?

**Comment by paolobriones** [comment]
i only really use BsonElementAttribute, but the naming is so off as compared to how the naming goes in mongodb-entities that i just had to request it

**Comment by dj-nitehawk** [comment]
[Field(...)] attribute added to v20.13.0-beta1
