### ISSUE TITLE
Change the static model to a dependency-injection friendly model

### ISSUE THREAD

**Issue by ahmednfwela** [dj-nitehawk/MongoDB.Entities#107]
Currently the library relies very much on the static `DB` class, which makes it simpler to use in the short term, but as the app scales bigger and unit tests are introduced, it becomes a nightmare to mock it.

and the `DBContext` class doesn't allow having a separate database/connection string from the static `DB` class

so I suggest making the `DBContext` inherit from a common interface `IDBContext` and make the static `DB` class use a default `DBContext` instance for users who still want to use the static version .

**Comment by dj-nitehawk** [comment]
i personally have a strong opinion against unit testing data access logic. if one must unit test, the recommended strategy is to wrap up/isolate all data logic inside your own repository or service classes and unit test those. 
even microsoft discourages people from mocking the EF DbContext
https://docs.microsoft.com/en-us/ef/core/testing/#unit-testing
however, i can add the ability to initialize a connection from within a DBContext instance.

**Comment by dj-nitehawk** [comment]
just pushed out a beta release: https://www.nuget.org/packages/MongoDB.Entities/20.14.0-beta4
now you can init connection from the constructor of DBContext like so:
```csharp
var db = new DBContext("db-name","localhost");
```
it has same overloads as DB.InitAsync
it will also defer connection until the first operation is performed.

**Comment by dj-nitehawk** [comment]
v20.14 released with a revised DBContext. with that there's no more need to access `DB` static methods if you don't want to.
