### ISSUE TITLE
Override Save Async

### ISSUE THREAD

**Issue by cloudb0x** [dj-nitehawk/MongoDB.Entities#11]
We follow Domain Driven Design and hence most of our entities have domain events attached to them.

Generally these are fired when a entity is saved and MediatR orchestrates the sending of them to their relevant domain event handlers. Currently we have to implement an interface which forces an enitity to implement its own `Save `or `SaveAsync `Method which then calls the base `Save `or `SaveAsync`From the Base `Entity` Class. 

It would be intuitive if instead of implementing our own interface we can override the base implementation and add our own logic ontop of it 

See an example below

    public class Dog : Entity
    {
        public string Colour { get; set; }  

        public string Name { get; set; }    

        public List<DomainEvents> { get; set; }  

        public override void Save()
        {
            //iterate over our domain events and dispatch here then save
             base.Save();
        }
    }

I would be happy to create a PR for this and add it in should you be open to this.

**Comment by dj-nitehawk** [comment]
the `Entity` base class does not have a `Save` method on it. currently `Save` is an extension method. so, it cannot be decorated with the `virtual` keyword to enable overriding.

but, i think the following will work for your case:

```csharp
        public class Dog : Entity
        {
            public string Colour { get; set; }
            public string Name { get; set; }
            public List<DomainEvents> DomainEvents { get; set; }

            public void Save()
            {
                //do whatever here...
                DB.Save(this);
            }

            public async Task SaveAsync()
            {
                //do whatever here...
                await DB.SaveAsync(this);
            }
        }
```
let me know if that won't work and why. then we can take it from there...

cheers!

**Comment by cloudb0x** [comment]
I see , We will just implement an interface that enforces those 2 methods on our entities for now. 
I will look through the codebase to understand it abit better and as to why this is an extension method , perhaps adding  a virtual method on the entity and calling the extension method from the base class will be a possibility?

**Comment by dj-nitehawk** [comment]
i can't remember for sure, but i think i went with the extension route, because properties (and or names) of the derived classes were not accessible (unknown) to the base class without a reference to the derived class being passed down to the base class `Save` method. extension was the best way to achieve what i wanted.
