### ISSUE TITLE
one-to-many relation loading with lookup performance

### ISSUE THREAD

**Issue by vihorlat** [dj-nitehawk/MongoDB.Entities#111]
Hello, 
I would just like to ask whether this one-to-many relation entities loading from DB ([the full code gist here](https://gist.github.com/dj-nitehawk/9971a57062f32fac8e7597a889d47714)):
```
            var authorWithBooks = await DB.Fluent<Author>()
                                          .Match(a => a.Name.Contains("Admin"))
                                          .Lookup<Author, Book, AuthorWithBooks>(
                                              DB.Collection<Book>(),
                                              a => a.ID,
                                              b => b.Author.ID,
                                              awb => awb.AllBooks)
                                          .ToListAsync();
```
performs faster than just looping and loading the related collection:
```
            var authors2 = await DB.Fluent<Author>().Match(a => a.Name.Contains("Admin")).ToListAsync();
            foreach (var aut in authors2)
            {
                // assign this to a non-database property in Author class e.g. 
                aut.BooksNonDB = await aut.Books.ChildrenQueryable().ToListAsync();
            }
```
`BooksNonDB ` could be a property in `Author` class:
```
    public class Author : Entity
    {
        [BsonIgnore]
        public ICollection<Book> BooksNonDB { get; set; }
        ....etc...
```

Thank you very much

**Comment by dj-nitehawk** [comment]
have a look at the benchmark results [here](https://mongodb-entities.com/wiki/Performance-Benchmarks.html#relationships).

source code [here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/848a70a31b280c67671e0d58c08c7539543ac30e/Benchmark/Benchmarks/Relationships.cs#L72)

as you can see, lookup is faster because it's a single db call.
the client-side join is also acceptable in some scenarios but always try to avoid doing db calls inside loops.

hope that answers your question.

**Comment by vihorlat** [comment]
Yeah, and how could I query a referenced property `Chapters` of a referenced property `Books` the correct, faster way, in one query, please? Is it possible?
[In an updated gist:](https://gist.github.com/vihorlat/c533998e364412e0b98ec7ecb8b20173)
```
    public class Book : Entity
    {
        public string Title { get; set; }
        public One<Author> Author { get; set; }
        public Many<BookChapter> Chapters { get; set; }

        public Book() => this.InitOneToMany(() => Chapters);
    }
```

```
            var authorWithBooksWithChapters = await DB.Fluent<Author>()
                                          .Match(a => a.ID == author.ID)
                                          .Lookup<Author, Book, AuthorWithBooks>(
                                              DB.Collection<Book>(),
                                              a => a.ID,
                                              b => b.Author.ID,
                                              awb => awb.AllBooks)
                                // lookup Book.Chapters ?
                                          .ToListAsync();
```

**Comment by dj-nitehawk** [comment]
well... in a real world app you wouldn't really need to display all authors with all their books and chapters right? typically, you'd have a separate db call to fetch all the chapters of a given book ID to load a book. ideally you'd be loading each chapter separately as it's just plain wasteful to transfer data across the wire which may not even be shown to the user.

but if you really must, you can do a nested lookup like [this](https://gist.github.com/dj-nitehawk/a2e2e59b063c2338b0b9507e209ec59e).

nested lookups are a bit complicated as you can see. basically the mongo query that needs to get generated is the following:
```
db.Author.aggregate(
    [
        {
            $lookup: {
                from: 'Book',
                let: { book_id: '$_id' },
                pipeline: [
                    {
                        $match: {
                            $expr: { $eq: ['$Author.ID', '$$book_id'] }
                        }
                    },
                    {
                        $lookup: {
                            from: 'Chapter',
                            localField: '_id',
                            foreignField: 'Book.ID',
                            as: 'AllChapters'
                        }
                    }
                ],
                as: 'AllBooks'
            }
        }
    ])
```
if you don't like the verbosity of the c# code, you can run the above mongo query using [this feature](https://mongodb-entities.com/wiki/String-Templates.html) of the library.
