### ISSUE TITLE
Introduce a new MigrateAsync that works with asp.net DI

### ISSUE THREAD

**Issue by ahmednfwela** [dj-nitehawk/MongoDB.Entities#112]
`MigrateAsync` currently does 2 things

1. Find classes that implement IMigration
2. Execute the migration logic

We can create a new overload for `MigrateAsync` that takes an `IEnumerable<IMigration>` as a parameter, and only executes the migration logic
e.g.
```cs
public static async Task MigrateAsync(IEnumerable<IMigration> migrationsEnumerable)
{
    var lastMigNum = (
        await DB.Find<Migration, int>()
              .Sort(m => m.Number, Order.Descending)
              .Limit(1)
              .Project(m => m.Number)
              .ExecuteAsync()
              .ConfigureAwait(false))
        .SingleOrDefault();

    var migrations = new SortedDictionary<int, IMigration>();

    foreach (var migration in migrationsEnumerable)
    {
        var t = migration.GetType();
        var success = int.TryParse(t.Name.Split('_')[1], out int migNum);

        if (!success)
            throw new InvalidOperationException("Failed to parse migration number from the class name. Make sure to name the migration classes like: _001_some_migration_name.cs");

        if (migNum > lastMigNum)
            migrations.Add(migNum, migration);
    }

    var sw = new Stopwatch();

    foreach (var migration in migrations)
    {
        sw.Start();
        await migration.Value.UpgradeAsync().ConfigureAwait(false);
        var mig = new Migration
        {
            Number = migration.Key,
            Name = migration.Value.GetType().Name,
            TimeTakenSeconds = sw.Elapsed.TotalSeconds
        };
        await DB.SaveAsync(mig).ConfigureAwait(false);
        sw.Stop();
        sw.Reset();
    }
}
```

This will allow more control over how to migrate the database

**Comment by dj-nitehawk** [comment]
added to v20.18.0-beta1

**Comment by ahmednfwela** [comment]
why don't we completely get rid of `(IMigration)Activator.CreateInstance(t)` ?

**Comment by ahmednfwela** [comment]
if we already have the instances of the `IMigration`, we don't need to cast them to type and then re-create them again

**Comment by dj-nitehawk** [comment]
then it becomes harder to abstract away the shared logic. don't wanna have to maintain duplicate (but slightly different) code. if you can come up with a way to not have dupe code, pls send in a PR.

honestly, i don't think it's that big of a deal as migrations are only ever run on app startup. right?

**Comment by ahmednfwela** [comment]
> then it becomes harder to abstract away the shared logic. don't wanna have to maintain duplicate (but slightly different) code. if you can come up with a way to not have dupe code, pls send in a PR.
> 
> honestly, i don't think it's that big of a deal as migrations are only ever run on app startup. right?

for me, i need to provide the migrations with an instance of UserManager, and in order to do that, I need to register them as transient and resolve them with asp.net DI

**Comment by ahmednfwela** [comment]
I will create a PR soon

**Comment by dj-nitehawk** [comment]
can;t you do `serviceProvider.GetService<ISomeService>()` from inside the migration?
i don't use asp.net anymore, so i don't remember much about how asp.net di works ;-)

**Comment by dj-nitehawk** [comment]
oh and when doing the PR, please add test to the tests project pls.

**Comment by dj-nitehawk** [comment]
gave it a bit more thought and i think i've sorted it. have a look
https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/MongoDB.Entities/DB/DB.Migrate.cs

pushed beta2 to nuget as well if you wanna give it a test run.

**Comment by dj-nitehawk** [comment]
v20.18 released with this feature
