### ISSUE TITLE
Can't find .InitOneToMany method for extended classes from :Entity

### ISSUE THREAD

**Issue by denileo82** [dj-nitehawk/MongoDB.Entities#117]
Hello,

I've installed MongoDB.Entities with Nuget.

DB.InitAsync is working...I can create flat documents and I can see them in Mongo database.

However, when I try to create a Many<> relationship I can't find .Hello,

I've installed MongoDB.Entities with Nuget.

DB.InitAsync is working...I can create flat documents and I can see into Mongo DB.

However, when I try to create a Many<> relationship I can't find .InitOneToMany method in my constructor.

I understand that this is an extension method, so all inherited from :Entity or :IEntity should be able to use this method.

see my code snipped below:

```
 public class Ship: MongoDB.Entities.Entity {
        public string Name { get; set; }

        public Ship() {
            
        }
    }

    public class Station : MongoDB.Entities.Entity {
        public string Name { get; set; }

        public MongoDB.Entities.Many<Ship> Ships { get; set; }

        public Station() {
//at this point, there is no .InitOneToMany
        }
    }
```

**Comment by dj-nitehawk** [comment]
you need to use the `this` keyword like so:
```csharp
public class Station : Entity
{
    public string Name { get; set; }
    public Many<Ship> Ships { get; set; }

    public Station()
    {
        this.InitOneToMany(() => Ships);
    }
}
```

**Comment by denileo82** [comment]
Also not working with this. in front of

**Comment by denileo82** [comment]
My bad...I had another namespace (package) starting with MongoDB

I've removed it or renamed it so it is working now.

congrats for your project, awesome :-)

**Comment by dj-nitehawk** [comment]
your project must have some problem. see here: https://streamable.com/mltwa5

**Comment by denileo82** [comment]
solved, see above :-)
