### ISSUE TITLE
Multiple exclusions ?

### ISSUE THREAD

**Issue by WhiteBookmark** [dj-nitehawk/MongoDB.Entities#12]
I am trying to use Projection in Find query but I can only use 1 exclusion, I am unable to use .Include("SomeField1").Exclude("SomeField2") as mentioned in the wikipages. I am actually looking for this:

```csharp
var UsersData = await DB.Find<Users>()
                                    .Project(Filter => Filter.Exclude(x => x.Field1).Exclude(x => x.Field2))
                                    .ExecuteAsync();
```

**Comment by dj-nitehawk** [comment]
that is an easy fix. just add the following import to your class:
`using MongoDB.Driver;`
i'll update the wiki regarding this as well.
thanks!

**Comment by WhiteBookmark** [comment]
Damn, and I spent hours trying to make it work :(
I gotta say ever since I have moved from Visual studio to vs-code, I am missing the c# intellisense features :(

**Comment by dj-nitehawk** [comment]
next time you run into something tricky, just open a new issue. i'll try my best to help out.
and, vs code is only good for front-end/js stuff imho. nothing beats vs2019 for c# ;-)
