### ISSUE TITLE
I don't understand to declare connection

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#120]
Should i declare connection in all method or at contrustction at once? if at constructers at only once than what means of async init?

```
   public CategoryController()
        {
            await DB.InitAsync("eCommerce",
                MongoClientSettings.FromConnectionString(
                    "mongodb+srv://xxxxx:xxxxx@cluster0.hcdor.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"));

        }
```

**Comment by JigarPrajpati** [comment]
Thanks a lot from by heart, may i know that if i start to use this lbirary, than there is only you're working so what about the future release, are you stop for new updates or will you continue or convert into paid version, will happy to use paid version too.

**Comment by dj-nitehawk** [comment]
thank you!

even though i'm the only maintainer there are community members contributing to the code base. for example, someone's contributing a massive rewrite with PR #125 these days.

even if i die tomorrow, anyone can easily make a fork and start releasing updates. that's the beauty of open source.

and this project will be always forever be OSS, there will never be a paid version.
