### ISSUE TITLE
One-To-Many relationships without join collections

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#131]
I can't use built in table relationship concept like Many/One-to-One,because it create new collection in database, but i've two different collection and want to join without LINQ, like by aggregation or lookup something how can i do with DB static class?

**Comment by dj-nitehawk** [comment]
if you don't want to use the built-in relationship features that use join-collections, you would have to embed the IDs of the foreign entities in a property and do lookups yourself like this:
```csharp
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using MongoDB.Entities;

await DB.InitAsync("test");

//create author
var author = new Author { Name = "author" };
await author.SaveAsync();

//create books
var books = new[] {
    new Book{ Title = "book 1", AuthorID = author.ID },
    new Book{ Title = "book 2", AuthorID = author.ID },
    new Book{ Title = "book 3", AuthorID = author.ID }
};
await books.SaveAsync();

//update author's BookIDs property
author.BookIDs = new[] {
    books[0].ID,
    books[1].ID,
    books[2].ID,
};
await author.SaveOnlyAsync(a => new { a.BookIDs });

//retrieve author including his books
var booksOfAuthor = await DB
    .Fluent<Author>()
    .Match(a => a.ID == author.ID)
    .Lookup<Author, Book, Author>(
        DB.Collection<Book>(),
        a => a.BookIDs,
        b => b.ID,
        a => a.LookedUpBooks)
    .SingleOrDefaultAsync();

Console.ReadLine();

public class Book : Entity
{
    public string Title { get; set; }

    [ObjectId]
    public string AuthorID { get; set; }
}

public class Author : Entity
{
    public string Name { get; set; }

    [ObjectId]
    public string[] BookIDs { get; set; }

    [IgnoreDefault]
    public List<Book> LookedUpBooks { get; set; }
}

```

**Comment by dj-nitehawk** [comment]
however, this approach has a limitation. your embedded IDs property should not grow unbounded. if one day it grows to be many millions, it might cause the document to grow beyond 16mb which is the bsondocument size limit in mongo. so it's best to use join-collections for storing relationships where you can foresee them growing to many millions.
