### ISSUE TITLE
Ability to save and get ID of saved entity

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#132]
![image](https://user-images.githubusercontent.com/82803338/142175978-4066173e-7a3a-4bd9-95ab-dc68b323baee.png)

Mostly we save entity like this, but it always void, instead of this please return the entity with new ID, so we can go ahead in a single line, mostly we have to separate this than we can access the ID, but it little more time taking, please consider this in new update, or help me if need something override to solve this issue.

Thanks man.

**Comment by dj-nitehawk** [comment]
you can use a simple extension method like this:
```csharp
public static class MyExtensions
{
    public static async Task<string> SaveEntity(this IEntity entity)
    {
        await entity.SaveAsync();
        return entity.ID;
    }
}
```
and save your entities like so:
```csharp
var bookID = await new Book { Title = "test" }.SaveEntity();
```

**Comment by JigarPrajpati** [comment]
I tried same approach, but it look like might be due to conversation into IEntity from Entity class data is not 
 saving to the database. 

![image](https://user-images.githubusercontent.com/91531559/143481207-f894c8fa-e06b-4f95-a287-178ea5739135.png)

If i don't use such method and simply save Entity class than it works fine, but if i use IEntity than it's not being saved to the database.

This is the step i following.

global using System;
```

public class Mongo : Entity, ICreatedOn, IModifiedOn
{
    public DateTime CreatedOn { get; set; }
    public DateTime ModifiedOn { get; set; }
    [AsObjectId]
    public string CompanyId { get; set; }
}

```
```

public static class OverrideMongoSave
{
    public static async Task<IEntity> SaveAndReturnAsync(this IEntity entity)
    {
        await DB.SaveAsync(entity);
        //entity.SaveAsync();
        return entity;
    }
}
```

**Comment by dj-nitehawk** [comment]
this works
```csharp
global using MongoDB.Entities;

await DB.InitAsync("test");

var ent = await new Mongo { CompanyId = "test" }.SaveAndReturnAsync();

Console.WriteLine(ent.ID);
Console.ReadLine();

public static class OverrideMongoSave
{
    public static async Task<TEntity> SaveAndReturnAsync<TEntity>(this TEntity entity) where TEntity : IEntity
    {
        await entity.SaveAsync();
        return entity;
    }
}

public class Mongo : Entity, ICreatedOn, IModifiedOn
{
    public DateTime CreatedOn { get; set; }
    public DateTime ModifiedOn { get; set; }
    [AsObjectId] public string CompanyId { get; set; }
}
```

**Comment by JigarPrajpati** [comment]
Amazing, Thanks it works 🎉
