### ISSUE TITLE
How to join and do condition or projection in One-To-One relationship

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#133]
![image](https://user-images.githubusercontent.com/91531559/142459013-703e8897-29f2-4d12-a64b-495b07dfbe83.png)

As dear sir, you can see here one-to-one binding happened, but how can i join that, i tried couple of LINQ & LAMDA with child collection, but didn't succeed, could you please help me to join in this case and retrieve value with condition or projection.

**Comment by dj-nitehawk** [comment]
I'm about to go to bed right now. can you post your entity classes
(simplified with only the relevant properties) and the expected result. I
will have a look at it tomorrow. because I can't make sense of what your
requirement is from what you have written.
