### ISSUE TITLE
DB instance only available in server side code, at razorpages frontend DB instance not available.

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#134]
![image](https://user-images.githubusercontent.com/82803338/142581741-90f36d4c-3759-427d-be47-d4e28d135142.png)

![image](https://user-images.githubusercontent.com/82803338/142581846-2968d46e-bb85-48b4-8db2-db37f8cb9d45.png)

![image](https://user-images.githubusercontent.com/82803338/142585201-2af15574-00f9-401e-914d-7144f4bb8ebc.png)

Also DBContext i tried, but it also not work at razor page.
![image](https://user-images.githubusercontent.com/82803338/142585875-04b59dd4-6588-4216-a485-363f38f26019.png)
![image](https://user-images.githubusercontent.com/82803338/142585949-dfb0e16b-0acf-4efb-bdf1-4861ed36efa1.png)

As you can see this is frontend razor page the DB instance not available, obviously backend side or controller level it's accessible, but not at razor page level please give me solution.

`Only backend side it work not front end`
![image](https://user-images.githubusercontent.com/82803338/142586817-f82ed12d-d918-4b0b-b50c-05ca0fc50d5f.png)

**Comment by dj-nitehawk** [comment]
i'm not familiar with razor pages.
but i assume you're missing import statements.
```csharp
@using MongoDB.Entities;
@using MongoDB.Driver;
@using MongoDB.Driver.Linq;
```
btw, isn't it considered bad practise to do data access code inside of ui code?
also you shouldn't use `ToList()` on the `Queryable` interface. because of [this reason](https://mongodb-entities.com/wiki/Async-Support.html).
better make use of `ToListAsync()`.

**Comment by jigarprajapatieastern** [comment]
Thanks, after add import in UI it works fine, also RazorPages actually run at server side first and return plain HTML, so no issue for data logic in razor pages. BTW i have  a question that if  i don't use ToListAsync() than also i can easily able to access all data, so it there any intense to use ToListAsync() insted of just use DB.Quryable<mMongo>() and looping the data over this?

**Comment by dj-nitehawk** [comment]
as explained in the doc site i linked. the mongodb driver is using `sync-over-async` internally for backwards compatibility when you do `ToList()`. which doesn't scale well and wastes resources/threads. so whenever possible, you should use `async/await` if you need your app to scale well. if you don't care about performance, you can use `ToList()`.
