### ISSUE TITLE
As we disucssed previosuly this error is everywhere, we have to solve find something.

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#136]
As i just do Any() on Quryable but that entity containct FuzzyString variable, JSON can't parse.

![image](https://user-images.githubusercontent.com/91531559/142649241-b70045bb-e934-417f-95c0-7fa0fdfe72ed.png)

One thing is sir, we can't project anytinh here, because it's just an Any() to check.

**Comment by dj-nitehawk** [comment]
I have already explained to you why it's happening in the previous post. your data in the db doesn't have the correct fuzzystring schema. you will have to either delete existing data or write a migration to correct the schema.

**Comment by dj-nitehawk** [comment]
also when querying fuzzystring with queryable, you can query the .Value property.

**Comment by dj-nitehawk** [comment]
if you still have trouble, show me how to reproduce the error with a minimal repro code. also it's better if you stop attaching screenshots and start posting text/code so I can easily try to reproduce the issues on my computer without having to spend too much effort to reproduce it.
