### ISSUE TITLE
how can i create unique value index in mongo..entitles

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#137]
how can i create unique value index in mongo..entites

**Comment by dj-nitehawk** [comment]
see documentation page
https://mongodb-entities.com/wiki/Indexes.html#indexing-options

**Comment by jigarprajapatieastern** [comment]
![image](https://user-images.githubusercontent.com/82803338/142668286-1c2679e6-d516-47df-addd-4d4a82914a24.png)
 it's not supporting any UniqueIndex, means no duplicate value allowed to add.

**Comment by dj-nitehawk** [comment]
https://stackoverflow.com/a/56314212/4368485
