### ISSUE TITLE
Storing an Entity type in multiple databases

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#139]
![image](https://user-images.githubusercontent.com/91531559/142719981-21d63d27-c9a4-46cc-9e02-71f141668f22.png)

Here everything works fine till mSection and it also save well in MasterDB (which is different database,) but after once initialize different database, next entity throw error means mSection saved in MasterDB well but mCategory,mParent & mChild say's MasterDB is not initilize.

**Comment by dj-nitehawk** [comment]
what you're trying to do is not supported. it's mentioned in the docs:

![screen-record-1637397462](https://user-images.githubusercontent.com/7043768/142720087-13412c25-a185-467e-82ea-a7687d245582.png)

**Comment by dj-nitehawk** [comment]
had another closer look at your screenshot.
it actually looks like you haven't initialized the connection for `MastersDB`.
you have only initialized `MasterDB`.
is this a typo or are you trying to use 2 different databases?
if using 2 dbs, just do another InitAsync call for "MastersDB" and it should work.
