### ISSUE TITLE
a bug with creating index

### ISSUE THREAD

**Issue by gshockim** [dj-nitehawk/MongoDB.Entities#14]
I'm a newbie with c# so I don't know why but some property expression shows as 

```
x => Convert(x.PropertyName)
```

and it emits 'PropertyName)' and made index wrong.
 
Here is my ragged fix with regex.
 
https://github.com/gshockim/Replica.MongoDB.Entities/commit/5e98c2e0098204d7f87a3bcf30cdac436835ecc3
   

And good to hear that multiple db supports! I'll check it later when have times.
Thanks!

**Comment by dj-nitehawk** [comment]
can you tell me what the property looks like in your code that breaks the function?
for ex:
`public SomeType PropName { get; set; }`

in other words, how to replicate the issue so i can write a test for it?

**Comment by gshockim** [comment]
```

namespace A.B.C
{
    namespace Record
    {
        public class D : MongoDB.Entities.Entity
        {
            public long F { get; set; }
            public string G { get; set; }
            public DateTime H { get; set; }
        }
    }
}
```

```
            db.Index<D>()
              .Key( x => x.F, KeyType.Descending )
              .Create();

            db.Index<D>()
              .Key( x => x.H, KeyType.Descending )
              .Create();

            db.Index<D>()
              .Key( x => x.G, KeyType.Descending )
              .Create();
```

It's confusing because this block of codes made it wrong in my private project but not happening in 'Examples' project.

![image](https://user-images.githubusercontent.com/43326888/66205807-54717180-e6e9-11e9-8fe9-8bc2fe93b41f.png)

You can see that it's expression shown as 'x => Convert(x.F)' in above screenshot.

**Comment by dj-nitehawk** [comment]
i can't produce the error with the latest v8.4.1

try this in a new console app and report back the result please?

```csharp
using MongoDB.Entities;
using System;

namespace A.B.C
{
    namespace Record
    {
        public class D : Entity
        {
            public long F { get; set; }
            public string G { get; set; }
            public DateTime H { get; set; }
        }

        public static class Program
        {
            public static void Main()
            {
                new DB("test-fullpath");

                DB.Index<D>()
                  .Key(x => x.F, KeyType.Descending)
                  .Create();

                DB.Index<D>()
                  .Key(x => x.H, KeyType.Descending)
                  .Create();

                var p1 = Prop.Dotted<D>(x => x.F);
                var p2 = Prop.Dotted<D>(x => x.H);

                Console.WriteLine("prop1 name is: " + p1); // F
                Console.WriteLine("prop2 name is: " + p2); // H
                Console.Read();
            }
        }
    }
}
```
are you testing with your own fork? it could be something wrong in your fork most likely. as everything seems to be working fine with mine.

**Comment by dj-nitehawk** [comment]
btw, the string replacement is not working because `name = null`. you need to find out somehow why it is null. i can't get it to become null on my machine no matter what i try.

**Comment by dj-nitehawk** [comment]
@gshockim good news... even though i couldn't replicate the issue, i was able to come up with regexes (with help from [stackoverflow](https://stackoverflow.com/questions/58245683)) to cater for all edge cases. have a look at the [Prop class here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/MongoDB.Entities/Utilities/Prop.cs).
