### ISSUE TITLE
I want to be part of this Entity to make it little more efficiant with some concept i having in my mind

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#140]
How can i join with you and start developing some more idea to add in this repo?

**Comment by JigarPrajpati** [comment]
Issue solved.

**Comment by JigarPrajpati** [comment]
Please add me as gorilladevelopment2021@gmail.com

**Comment by dj-nitehawk** [comment]
https://www.dataschool.io/how-to-contribute-on-github/ 

you can submit a PR as explained in the above article. 
but there's no guarantee that your changes will be accepted/merged. particularly if your changes breaks the existing public API or fails existing tests or results in performance regressions.
