### ISSUE TITLE
Is there anything something futureQuery do you having?

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#141]
I seen EF plus support future query means collection of query like count, distinct, aggregation and main data are go to single query, so not 4 times query required to call. so do you have any support like all operation done in bulk?

**Comment by dj-nitehawk** [comment]
mongo only has bulking of the same kind of command. for ex: you can batch save or batch updates. that's all we have over in mongo world.
