### ISSUE TITLE
Ability to close the connection if connection was initialized after `DB.InitAsync()`

### ISSUE THREAD

**Issue by anthopark** [dj-nitehawk/MongoDB.Entities#143]
Hello,

I'm trying to unit test a service that depends on a repository object with Mongo2Go and Xunit.
Is there a way for the DB instance to close its connection?

As I'm using Xunit, I want my Mongo2Go runner to be constructed and destructed for each test case.
I have a problem connecting to a new Mongo2Go runner after the first test case and I'm assuming the `DB` is still connected to the already destructed Mongo2Go runner from the previous test case.

I'm a junior coder and would appreciate any insights related to the issue.

Thank you!

**Comment by dj-nitehawk** [comment]
i believe you need a collection fixture like this:
```csharp
public class DatabaseFixture : IDisposable
{
    private MongoDbRunner _runner;

    public DatabaseFixture()
    {
        _runner = MongoDbRunner.Start();

        DB.InitAsync(
            "test-database",
            MongoClientSettings.FromConnectionString(_runner.ConnectionString));
    }

    public void Dispose()
    {
        _runner.Dispose();
    }
}

[CollectionDefinition("Mongo2Go")]
public class CollectionFixture : ICollectionFixture<DatabaseFixture> { }

[Xunit.Collection("Mongo2Go")]
public class RepositoryTests
{
    private BookRepository _bookRepo = new();

    [Fact]
    public async Task Saving_A_Book_Works()
    {
        var guid = Guid.NewGuid().ToString();
        await _bookRepo.SaveBook(new Book { Title = guid });
        var book = await _bookRepo.GetByTitle(guid);
        Assert.Equal(guid, book.Title);
    }
}
```

**Comment by dj-nitehawk** [comment]
you can have true isolation between tests with a database per test stratergy like so:
```csharp
public class DatabaseFixture : IDisposable
{
    private readonly MongoDbRunner _runner;
    public MongoClientSettings? ClientSettings { get; set; }

    public DatabaseFixture()
    {
        _runner = MongoDbRunner.Start();
        ClientSettings = MongoClientSettings.FromConnectionString(_runner.ConnectionString);
    }

    public void Dispose() => _runner.Dispose();
}

[CollectionDefinition("Mongo2Go")]
public class CollectionFixture : ICollectionFixture<DatabaseFixture> { }

[Xunit.Collection("Mongo2Go")]
public class RepositoryTests
{
    private readonly BookRepository _bookRepo = new();
    private readonly MongoClientSettings? _clientSettings;

    public RepositoryTests(DatabaseFixture fixture)
    {
        _clientSettings = fixture.ClientSettings;
    }

    [Fact]
    public async Task Saving_A_Book_Works()
    {
        var guid = Guid.NewGuid().ToString();
        await DB.InitAsync(guid, _clientSettings);
        await _bookRepo.SaveBook(new Book { Title = guid });
        var book = await _bookRepo.GetByTitle(guid);
        Assert.Equal(guid, book.Title);
    }
}
```

**Comment by dj-nitehawk** [comment]
btw, what you're actually doing is integration testing. so you should just consider testing all the way out from endpoint/controller level instead of trying to test just at service/repo level. life will be much easier with proper integration testing.

**Comment by anthopark** [comment]
Thank you very much for taking the time to lay out a few different solutions. I do think you have a point on just integration testing the endpoint would save. The only concern is to feed the application with a different setting but I'll refer to the link you shared in my comment in your DEV post. The least I can do is buy you a coffee for your outstanding help! Thank you.

**Comment by dj-nitehawk** [comment]
thank you! received the coffee 🙏
WAF (WebApplicationFactory) is the way to go if you need to integration test with a different set of configuration/settings. 
here's example: https://github.com/dj-nitehawk/FastEndpoints/blob/dcdad6631acd95ac0c7763a47ed2c2fa82952065/Test/Setup.cs#L12 
that project uses my other library FastEndpoints but the concept would be the same for mvc as well.
