### ISSUE TITLE
How to join one to one

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#145]
I seen your document, but couldn't find a well structured understandable document to join one-to-one relationship in LINQ.

I've something this
![image](https://user-images.githubusercontent.com/91531559/144421399-1081a1a0-079d-4fa9-9b3f-a1774e38721d.png)

and i want this mProduct table comes with mCompany too. so what the approach can i use with LINQ?

**Comment by dj-nitehawk** [comment]
see #118
