### ISSUE TITLE
Many<TChild>.RemoveAsync(IEnumerable<string> childIDs) seems to only remove one child entity reference

### ISSUE THREAD

**Issue by bucky3000** [dj-nitehawk/MongoDB.Entities#146]
I tried using `Many<TChild>.RemoveAsync(IEnumerable<string> childIDs)` and supplied it two childIDs, but only one child reference ever gets deleted from the collection. If I call `Many<TChild>.RemoveAsync(string childID)` for each childID, it removes both.

**Comment by dj-nitehawk** [comment]
thanks for reporting...
it was a minor oversight in the code.
fixed with the latest release.

**Comment by bucky3000** [comment]
Thank you!
