### ISSUE TITLE
Documentation update for Transactions

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#148]
We need to update the API documentation to specify that DB.Transaction() requires mongodb to be setup as a replica set or in a cluster otherwise calling DB.Transaction() will yield an exception "Standalone servers do not support transactions."

**Comment by paolobriones** [comment]
In my situation, i am running mongodb thru docker for development (single node), but in production, i am running a replica set of several nodes, however, my deployed code is incompatible with my setup in development

**Comment by dj-nitehawk** [comment]
yeah I'll add a note on how to create a single node replicaset for development/testing. 

btw do you by any chance know how to enable replicaset together with authentication in docker? I asked on stackoverflow but didn't get any answers: https://stackoverflow.com/q/64613147/4368485

**Comment by paolobriones** [comment]
negative, I've never gotten that to work in docker
