### ISSUE TITLE
DB.Delete<T>(x => x.Name == "") only deletes 1 record

### ISSUE THREAD

**Issue by Seyden** [dj-nitehawk/MongoDB.Entities#15]
Hey,

when you currently call DB.Delete<T>(x => x.Name == "")  with a predicate, it only deletes the first occurence found in the database.

Expected behaviour:
Delete all occurences with the specific predicate.

Btw.. calling DB.Collection<T>().DeleteMany(x => x.Name == ""); works fine, just to point it out.

**Comment by dj-nitehawk** [comment]
good catch!!!
fixed with v8.8
thanks for reporting... highly appreciated :-)
