### ISSUE TITLE
GridFS: using the same Queryable<T>() on a collection of FileEntity

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#150]
Currently, for file storage, to query a collection of `FileEntity` classes, we have to use `DB.Find()` instead of the normal way of using `DB.Queryable<T>()`.

Is there a way to merge this functionality into the API? so that regular entities and file entities are queried the same way

**Comment by dj-nitehawk** [comment]
queryable does work with file entities
```csharp
var res = await DB
    .Queryable<Picture>()
    .Where(p => p.Width > 100 && p.Height > 100)
    .SingleOrDefaultAsync();

public class Picture : FileEntity
{
    public string FileName { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
}
```
`FileEntity` is a sub class of `Entity` so querying is no different.

retrieving the file's binary data directly with the file ID is only available via `DB.File<T>("ID")`

`DB.File<T>()` cannot support any other querying because no other entity related metadata is present in the binary chunks collection.

**Comment by paolobriones** [comment]
Happy New Year!

i tried it out exactly in your previous response:

```
public class Picture : FileEntity {
    public string FileName { get; set; }
    public int Width { get; set; }
    public int Height { get; set; }
}
...
var res = await DB.Queryable<Picture>()
                  .Where(p => p.Width > 100 && p.Height > 100)
                  .SingleOrDefaultAsync();
```

I was getting a compile-time error:
**'Picture' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'Picture' could be found.**

Not sure if I'm missing something, maybe because it's the new year?? :)

MongoDB.Entities v20.26.1

**Comment by dj-nitehawk** [comment]
can you run [this console project](https://github.com/dj-nitehawk/MongoDB.Entities/files/7797524/Mongo.zip)?

if that works, and your project still can't; i'm gonna need a minimal repro project from you to debug.

**Comment by paolobriones** [comment]
oh shoot!

sorry about that, the issue was the missing 

`using MongoDB.Driver.Linq;`

thanks!
