### ISSUE TITLE
Support for UpdateAndGetMany?

### ISSUE THREAD

**Issue by BenStorey** [dj-nitehawk/MongoDB.Entities#151]
Hello,

This library is really great, thanks for your work on it. 

Is there a way to update a bunch of documents, and get all the updated documents back in one call? I can Update many easily enough, and I can UpdateAndGet the first changed document - but it would be nice if I were able to get back all the changed documents?

At least, I can't see anything in the API documentation that indicates this is possible...?

Thanks!

**Comment by dj-nitehawk** [comment]
thanks!

sadly, mongo driver nor the mongo server offer a way to do that in a single call. so i'm afraid it's always gonna be a 2 query operation.

**Comment by BenStorey** [comment]
Okay got it - thanks a lot for coming back so fast.
