### ISSUE TITLE
Issue after updating Mongo libraries

### ISSUE THREAD

**Issue by almostEric** [dj-nitehawk/MongoDB.Entities#156]
Hi,

Mongo updated their driver to 2.15.1
Now when I try to use the GeoCoordinates2D object, I am getting "can't find mongo .... version 2.15.0" error

**Comment by almostEric** [comment]
Hi, Is there anyway you can get rid of hard coded references to MongoDB versions? (or at least make them >=).
Your new version worked fine until Mongo released the 2.17.0 drivers :(

**Comment by dj-nitehawk** [comment]
question is why is this happenning only to you?
official driver getting updated should have nothing to do with what version reference this library has to it.
just remove all references you have in your csproj files to the official driver and everything should just work.
or do you have sort of weird project setup?

**Comment by almostEric** [comment]
Nothing weird about my project setup. I notice that if I remove the mongo references and allow your package to install its dependencies, it uses version 2.16.1 of the drivers which are *not* the latest.

I have plenty of other nuget packages where I have also installed the dependency package as well (you realize how many things depend on Newtonsoft.Json). Never had an issue like this

**Comment by dj-nitehawk** [comment]
the thing is it's not safe to do the >= version as newer versions have not yet been tested with the library. there are sometimes small breaking changes between minor version upgrades of the driver and may lead to data loss. that's why the driver version is fixed at the last one that has been tested/known to work good with this library.

is there something else in your projects that references/pulls down the latest driver version?

**Comment by almostEric** [comment]
I guess it just me, but I would rather be able to run the latest versions of all my libraries and then downgrade if necessary. As it is you are forcing us to use outdated libraries which you must assume were updated for a reason.

 

Anyway, in general, Mongo is very good about not making breaking changes.

**Comment by dj-nitehawk** [comment]
so do i. i usually need about a week to test out the latest versions and do a release.
in case i miss a version, you can open an issue in the future and i'll do my best to get an update as fast as i can.
have a good day!
