### ISSUE TITLE
How to remove sub array element

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#157]
Hi nitehawk.
love you from india.

I want to update sub element of array, i did this but don't know how to filter by ID of subarray and update that element.
![image](https://user-images.githubusercontent.com/91531559/168469853-24eed9aa-f8b2-438a-bf02-7c5d7d40527a.png)

I want to update one step element of step array with ID filter how can i do it?

Second Question.
how can i also update deeply inner subarray with filter too, i tried but i failed to do it
![image](https://user-images.githubusercontent.com/91531559/168586675-23c913b6-a6cc-48e4-a34f-cb8b55246f23.png)

**Comment by dj-nitehawk** [comment]
for updating first level arrays, you can just do the following:
```csharp
public class Parent : Entity
{
    public Child[] Children { get; set; }
}

public class Child
{
    public int Id { get; set; }
    public string Name { get; set; }
}

await DB
    .Update<Parent>()
    .Match(p => p.ID == "001" &&
                p.Children.Any(c => c.Id == 2))
    .Modify(p => p.Children[-1].Name, "updated")
    .ExecuteAsync();
```

the `[-1]` is a special mongodb driver notation which refers to the `first` matched item in the previous `Any()` predicate.

for multi-level/deep nested array updates, you can only do so with `array filters` for which there's no type-safe way. see following SO question for some pointers: https://stackoverflow.com/questions/65473900

**Comment by dj-nitehawk** [comment]
for sub element removal, you can use pullfilter
```csharp
await DB
    .Update<Parent>()
    .Match(p => p.ID == "001")
    .Modify(b => b.PullFilter(p => p.Children, c => c.Id == 2))
    .ExecuteAsync();
```

**Comment by JigarPrajpati** [comment]
![image](https://user-images.githubusercontent.com/91531559/169289649-b8f330aa-cca2-417a-8887-e2aacfb57ad5.png)

this is one level only, i need to two times filter for second array filter & third filter array. first level i can do it by MatchID, but how for second and third inside a second array?

**Comment by dj-nitehawk** [comment]
> for multi-level/deep nested array updates, you can only do so with `array filters` for which there's no type-safe way. see following SO question for some pointers: https://stackoverflow.com/questions/65473900

see above SO for more info and see here for an example: 
https://mongodb-entities.com/wiki/Entities-Update.html#array-filter-updates
and 
https://mongodb-entities.com/wiki/String-Templates.html#update-with-array-filters
