### ISSUE TITLE
How to find record with contain keyword?

### ISSUE THREAD

**Issue by jigarprajapatieastern** [dj-nitehawk/MongoDB.Entities#161]
I have Cortyard hotel in my database, and i want to search it with 'cort' or 'yard'. i tried this

` return new JsonResult(DB.Find<tblUsers>().MatchExpression("{'HotelName' : /.*"+ name + ".*/i}"));
`
i tried with Lamda Contain too, but not able to find the data, please note, i don't want any fuzzy index.

**Comment by dj-nitehawk** [comment]
try this: https://github.com/dj-nitehawk/MongoDB.Entities/issues/21#issuecomment-562644330
