### ISSUE TITLE
I would update or insert a whole record not a sub record.

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#163]
Hi nitehawk.
I can easylu insert or update sub record, but i don't know how to do for a whole collection itself.

 ```
public class tblTables : Entity
    {
        public string Group { get; set; }
        public string Name { get; set; }
        public string ClientID { get; set; }
    }
```
 `await DB.Update<tblTables>().Modify(x=>x.SetOnInsert(table))`

Sometimes the modal comes with ID value and sometimes not, so i want to insert or set automatically without use of DB.Update.
please help me

**Comment by dj-nitehawk** [comment]
question is unclear
pls explain further with code example

**Comment by JigarPrajpati** [comment]
Dear sir i'm saying that, how can i insert or update a record with single method like InsertOrUpdate for a whole entity?

**Comment by dj-nitehawk** [comment]
i believe you're asking about how to do an `upsert`

```csharp
await new tblTables { ID = "one", Name = "created one" }.SaveAsync();

await DB
    .Update<tblTables>()
    .MatchID("one")
    .ModifyWith(new tblTables { ID = "one", Name = "updated one" })
    .Option(o => o.IsUpsert = true)
    .ExecuteAsync();

await DB
    .Update<tblTables>()
    .MatchID("two")
    .ModifyWith(new tblTables { ID = "two", Name = "created two" })
    .Option(o => o.IsUpsert = true)
    .ExecuteAsync();
```

if the match is being done on the `ID`, you can simply use `.SaveAsync()` on the entity, as it does the same thing.
https://mongodb-entities.com/wiki/Entities-Save.html#save-an-entity

**Comment by azhe403** [comment]
Hi, when i using following snippet, CreatedOn field not updated on first insert. 
It is bug?

>```cs
> await DB
>     .Update<tblTables>()
>     .MatchID("two")
>     .ModifyWith(new tblTables { ID = "two", Name = "created two" })
>     .Option(o => o.IsUpsert = true)
>     .ExecuteAsync();
