### ISSUE TITLE
How to Sync local MongoDB data to Server MongoDB

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#165]
I'm in one trouble where we made the asp.net core application online first, buy after client say they need offline, so we thought to use Advanced Installer to package the webApplication into .Exe and install MongoDB locally automatically by help of Advanced Installer. 

Now Client need at the end of the day all the data from mobile view, so i requried to sync all the data of local MongoDB to Server MongoDB database.

How can i do this dear sir?

**Comment by dj-nitehawk** [comment]
since i haven't done that myself, you will have to talk to mongodb to see if they have some sort of solution for this requirement.
maybe some service like this: https://www.mongodb.com/docs/atlas/app-services/sync/learn/overview/#std-label-sync-overview
