### ISSUE TITLE
Yes sir i knew it thanks you but i've such following trouble, where i want to get only isDeleted==false record, but i can't get any entry.

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#170]
Yes sir i knew it thanks you but i've such following trouble, where i want to get only isDeleted==false record, but i can't get any entry.

```
public class tblOrder : Entity
{
  public Items[] Items { get; set; }
}
public class Items : Entity
 {
 public bool isDeleted { get; set; } = false;
}

```

  `  return Ok(await DB.Find<tblOrder>().Match(x => x.ID == orderInternalID && x.Items[0].isDeleted==false).ExecuteFirstAsync());
        `

1 record
![image](https://user-images.githubusercontent.com/91531559/175513472-84004209-3a07-42b6-8231-b03081105b46.png)

2 record
![image](https://user-images.githubusercontent.com/91531559/175513513-bfd52e9c-dfe3-4524-81cf-13ac49bc19ef.png)

_Originally posted by @JigarPrajpati in https://github.com/dj-nitehawk/MongoDB.Entities/issues/169#issuecomment-1165426374_

**Comment by dj-nitehawk** [comment]
sorry mate, don't have the time to help with mongo queries.
pls ask this type of questions on stackoverflow as it's not directly related to the library.
will try to answer when i get some free time.
