### ISSUE TITLE
I can't able to modify date

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#172]
```
 public class PromotionalDiscount : Entity, ICreatedOn
    {
        public Date ExpiredOn { get; set; } = DateTime.UtcNow;

        public DateTime CreatedOn { get; set; } = DateTime.Now;
     
        public int Discount { get; set; }
    }

```
`            await DB.Update<tblUsers>().Match(x=>x.ID==User.Identity.Name && x.PromotionalDiscounts.Any(p => p.ID == id)).Modify(x => x.Set(f => f.PromotionalDiscounts[-1].ExpiredOn, DateTime.Now)).ExecuteAsync();
`
i getting this error here
![image](https://user-images.githubusercontent.com/91531559/177013070-cf34c002-a3bd-4947-9c9a-839bde0c6d88.png)

**Comment by dj-nitehawk** [comment]
sorry mate, don't have the time to help with mongo queries.
pls ask this type of questions on stackoverflow as it's not directly related to the library.
will try to answer when i get some free time.
