### ISSUE TITLE
How to filter on projection (server side)

### ISSUE THREAD

**Issue by JigarPrajpati** [dj-nitehawk/MongoDB.Entities#173]
How to fetch sub record with projection or without projection?
I want all items with filter and get only those record from tblorder.items

```
 var item = await DB.Find<tblOrder,Items>().Match(x => x.ClientID == User.Identity.Name && x.Items.Any(p=>p.ID==dishId) )
                .Project(x => x.Items)
                .ExecuteAsync();
```

```
public class tblOrder : Entity
    {
        public List<Items> Items { get; set; } = new List<Items>();
    }
```

I want to filter on  .Project(x => x.Items.where(x=>x.ID=="1"))

**Comment by dj-nitehawk** [comment]
sorry mate, don't have the time to help with mongo queries.
pls ask this type of questions on stackoverflow as it's not directly related to the library.
will try to answer when i get some free time.
