### ISSUE TITLE
Need Update Driver to 2.16.1

### ISSUE THREAD

**Issue by azhe403** [dj-nitehawk/MongoDB.Entities#175]
Currently, this Lib using driver version 2.15
I got this error when running app (in this case is serverless instance of mongodb).

![image](https://user-images.githubusercontent.com/17938038/179373509-6ad68aaf-5983-4898-ae84-2c3e0f89d093.png)

After explicit install driver to 2.16.1, no error occurred and app can run without problem.
Based on this Jira: https://jira.mongodb.org/browse/CSHARP-3963, fixes for this issue is available at driver version 2.16.1.

thanks

**Comment by dj-nitehawk** [comment]
`v20.26.4` has been pushed to nuget
