### ISSUE TITLE
Not able to set null as value for the tag using string template

### ISSUE THREAD

**Issue by ammar91** [dj-nitehawk/MongoDB.Entities#177]
I have a scenario where the db field could potentially be set to null. But when trying to do so using template, getting an error.
```

public async Task UpdateResellerMargin(string tenantId, decimal? resellerMargin)
{

        var pipeline = new Template<Tenant>(@"
                [
                    { $set: { '<Settings.ResellerMargin>': <reseller_margin> } }
                ]
            ")
         .Path(t => t.Settings.ResellerMargin)
         .Tag("reseller_margin", resellerMargin.ToString());


        await DB.Update<Tenant>()
           .Match(t => t.ID == tenantId)
           .WithPipeline(pipeline)
           .ExecutePipelineAsync();
}
```

when a value for the tag `<reseller_margin>` pass other than null it works, but in case of null it fails with the error message 

`JSON reader was expecting a value but found '}'.
`

Any help on this would be appreciated.

**Comment by dj-nitehawk** [comment]
try something like this:
```csharp
.Tag("reseller_margin", resellerMargin == null ? "null" : resellerMargin.ToString());
```

**Comment by ammar91** [comment]
Yes, that works. Thank you

just find bit off to pass it as string literal though, wouldn't it be nice to pass null as a value without quotes?

Also since Tag method only accept string as a value, what if one want to pass object, array,  or array of object as a value?

**Comment by dj-nitehawk** [comment]
will look in to it when i get some free time.
thanks!
