### ISSUE TITLE
.net core 6

### ISSUE THREAD

**Issue by avarndell** [dj-nitehawk/MongoDB.Entities#179]
Are there plans to get this updated to work with .net core 6?

**Comment by dj-nitehawk** [comment]
this a .net standard library
https://github.com/dj-nitehawk/MongoDB.Entities/blob/34e9416b2c373e69e0a506ce7458084b3d689428/MongoDB.Entities/MongoDB.Entities.csproj#L7

so it already works with any .net 6 project. 

I have at least eight .net 6 project with this library in production 😉

**Comment by bryanmillerph** [comment]
mongodb.entities works really well with dotnet6, i am currently using this in production handling millions of documents in mongodb.
