### ISSUE TITLE
which index will .Option apply on?

### ISSUE THREAD

**Issue by li-zheng-hao** [dj-nitehawk/MongoDB.Entities#181]
```c#
 DB.Index<Model>()
                .Key(it => it.A, KeyType.Ascending)
                .Key(it => it.B, KeyType.Ascending)
                .Option(o => { o.Unique = true; })
                .CreateAsync();
```
hello i just started using this library，in the above case，will unique attribute apply on A or B or Both?

**Comment by dj-nitehawk** [comment]
> specify index keys by chaining calls to the .Key() method. compound indexes are created by calling the .Key() method multiple times.

so when you call `.Key()` multiple times, you're creating a compound index.
so the uniqueness applies to the compound index as a whole.

to create single key indexes, just call `.Key()` once per each `.CreateAsync()` call.
