### ISSUE TITLE
FileEntity.Data.DeleteBinaryChunks() quirks

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#182]
Hi nitehawk, 

I was recently using the DeleteBinaryChunks() method of FileEntity, and was getting some strange behavior.

Calling DeleteBinaryChunks() deletes the actual file in mongodb **BUT the underlying entity has to be manually updated and requeried afterwards**. Otherwise, any other operation on the entity will still have the file-related metadata in it.

```csharp
// Assume that an existing entity with an associated file is already in mongodb
SomeEntity entity = DB.Find<SomeEntity>().Match(i => i.ID == id).ExecuteSingleAsync();

// This call successfully deletes the file from mongodb
entity.Data.DeleteBinaryChunks();

// This entity still has the old FileEntity metadata before the DeleteBinaryChunks() call
entity.SomeProperty = "Some Value";
entity.SaveAsync();
```

so my current workaround is to do something like:

```csharp
// Assume that an existing entity with an associated file is already in mongodb
SomeEntity entity = DB.Find<SomeEntity>().Match(i => i.ID == id).ExecuteSingleAsync();

entity.Data.DeleteBinaryChunks();
entity.SaveAsync();
entity = DB.Find<SomeEntity>().Match(i => i.ID == id).ExecuteSingleAsync();

// The entity is fine to continue operating on
entity.SomeProperty = "Some Value";
entity.SaveAsync();
```

What do you think?
Maybe DeleteBinaryChunks() should update the entity internally and return the updated entity back to the caller

**Comment by dj-nitehawk** [comment]
if i remember correctly `DeleteBinaryChunks()` is an undocumented method and if someone's using it, they should take care to also update/delete the entity also.

will investigate if something can be done about this. 

thanks!

**Comment by dj-nitehawk** [comment]
just delete it and create a new one (which automatically deletes the chunks as well).

**Comment by dj-nitehawk** [comment]
or if you wanna update the binary data, just upload via the same file entity. which automatically deletes the old chunks.

**Comment by dj-nitehawk** [comment]
just tried the example from the docs and it creates and deletes the file and chunks by doing the following:
```cs
using MongoDB.Entities;

await DB.InitAsync("test");

var kitty = new Picture
{
    Title = "NiceKitty.jpg",
};

await kitty.SaveAsync();

var streamTask = new HttpClient().GetStreamAsync("https://placekitten.com/g/300/300");

using (var stream = await streamTask)
{
    await kitty.Data.UploadAsync(stream);
}

await kitty.DeleteAsync();

public class Picture : FileEntity
{
    public string Title { get; set; }
}
```
throw that in a new console project and see if it doesn't delete the chunks and entity for you.
update the above to reproduce the issue you're having if possible.

**Comment by dj-nitehawk** [comment]
also calling `UploadAsync()` on an already saved file entity always makes sure any old chunks are deleted before new binary data is uploaded:
https://github.com/dj-nitehawk/MongoDB.Entities/blob/10c6591c79176925215e4d8317b3564e6465da40/MongoDB.Entities/Core/FileEntity.cs#L177-L182

**Comment by dj-nitehawk** [comment]
why not just re-upload using the same entity?
```cs
//initial upload

await kitty.SaveAsync();

var streamTask = new HttpClient().GetStreamAsync("https://placekitten.com/g/300/300");

using (var stream = await streamTask)
{
    await kitty.Data.UploadAsync(stream);
}

//retrieve the existing file and upload again
//which clears the old data automatically.

var nicekitty = await DB
    .Find<Picture>()
    .MatchID(kitty.ID)
    .ExecuteSingleAsync();

streamTask = new HttpClient().GetStreamAsync("https://placekitten.com/g/400/400");

using (var stream = await streamTask)
{
    await nicekitty.Data.UploadAsync(stream);
}
```
the only thing is you gotta be careful not to upload data for the same file entity simultaneously from multiple places/ threads. if that is the requirement, you need to use some sort of queue or locking.
