### ISSUE TITLE
About the MongoDB.Driver.Linq.ExpressionNotSupportedException

### ISSUE THREAD

**Issue by thepra** [dj-nitehawk/MongoDB.Entities#193]
I'm getting quite many of those exceptions when using more or less complex `Match(e => <condition>)`, ex:
> DB.Find\<User\>().Match(u => workersRolesFilter.Contains(u.Role.Name) && u.DeletionDate == null).ExecuteAsync(token);

Am I supposed to use instead `DB.Queryable<User>() .Where(...)` for such queries? If yes, what are the limits of `Match(e => ...)`?

**Comment by thepra** [comment]
It's weird, it's as if despite throwing `MongoDB.Driver.Linq.ExpressionNotSupportedException` it does return in the end a valid and filtered result...
And `Queryable<T>()` doesn't help either.
Should I ignore this exceptions?

**Comment by dj-nitehawk** [comment]
gonna need a self contained repro to look in to this. it doesn't seem to throw with stuff i tried.
