### ISSUE TITLE
ReadName can only be called when State is Name, not when State is EndOfDocument.

### ISSUE THREAD

**Issue by Ebi1989** [dj-nitehawk/MongoDB.Entities#199]
When the DownloadAsync method is used, the following error occurs
**ReadName can only be called when State is Name, not when State is EndOfDocument.**

After changing the following codes, the error was fixed:
1- var findTask =
            session == null
            ? chunkCollection.FindAsync(x => x.FileID == parent.ID)
            : chunkCollection.FindAsync(x => x.FileID == parent.ID);

2- await stream.WriteAsync(chunk.Data, 0, chunk.Data.Length, cancellation).ConfigureAwait(false);

**Comment by dj-nitehawk** [comment]
pls see: https://github.com/dj-nitehawk/MongoDB.Entities/issues/198#issuecomment-1453534566
