### ISSUE TITLE
Sync over async - deadlock issue

### ISSUE THREAD

**Issue by sundna** [dj-nitehawk/MongoDB.Entities#20]
Hello,

we are experiecing deadlock issues calling a synchronous metod (Execute()) of your library in our Web API application.
Checking the code, we found the sync method calls the async implementation (i.e. ExecuteAsync()) using the wrong pattern GetAwaiter().GetResult().

As workaround, we call the async method wrapping it into a Task.Run "statement", but we noticed other methods have the same issue (Save, ...).

We changed the method as follow and it works for us:

public List<TProjection> Execute()
{
     return Task.Run(async () => await ExecuteAsync()).GetAwaiter().GetResult();
}

Can you check and fix all the sync over async implementation in order to avoid deadlock scenarios, please?

Regards

**Comment by dj-nitehawk** [comment]
i will have a look at it asap.
in the meantime, pls let me know if you're using classic .net framework or .net core and what version.
thanks!

**Comment by sundna** [comment]
Sorry, I forgot to mention that we are using .NET 4.6.2
Thanks!

**Comment by dj-nitehawk** [comment]
ah i see... the library started off only supporting .net core where `GetAwaiter().GetResult()` doesn't cause deadlocking. classic framework support was added recently and it completely missed my radar. i will fix this within the next day or two and push an update. thanks for bringing it to my attention.

**Comment by sundna** [comment]
ok thanks!
i will wait for ur fix :)

**Comment by dj-nitehawk** [comment]
just pushed v8.13 to nuget which should take care of the deadlock issue.
pls ugrade and give it a test run.

**Comment by sundna** [comment]
good job work fine :)
Thanks  a lot
