### ISSUE TITLE
DeleteAsync is Acknowledged but DeletedCount is always zero

### ISSUE THREAD

**Issue by Germandf** [dj-nitehawk/MongoDB.Entities#200]
Greetings,

After #198 , I updated to `v21.0.2.5-beta`. Now, the previous exception is not thrown but, as the title says, the `DeleteResult` is Acknowledged but DeletedCount is always zero.

Here is how I call the method:

``` csharp
var result = await _dbContext.CurrentContext.DeleteAsync<PendingJobDated>(id);
```

I even tried changing it using a lambda expression but there is no difference.

``` csharp
var result = await _dbContext.CurrentContext.DeleteAsync<PendingJobDated>(x => x.ID == id);
```

Just in case, I did verify that the id is arriving correctly until my repository layer and it corresponds to the Entity in the Db (`642ac500776a62a3463f4ddb`).

![image](https://user-images.githubusercontent.com/69018178/229516806-4d1aa5fe-f79d-46f4-96cb-1e4053c836bc.png)

Anyways, as mentioned in #198, the code is the same as before the problem started.

Let me know if I'm missing something.

**Comment by dj-nitehawk** [comment]
i'm getting the count correctly when i try the following:
```cs
using MongoDB.Entities;

await DB.InitAsync("test");
var db = new DBContext();
var person = new Person { Name = "test" };
await db.SaveAsync(person);
var count = (await db.DeleteAsync<Person>(person.ID)).DeletedCount;
Console.Read();

public class Person : Entity
{
    public string Name { get; set; }
}
```
update it and send back to replicate the issue, without any of your intermediate layers that is.
if the bare minimum above works, it's most likely an issue somewhere in your layers.

**Comment by Germandf** [comment]
The code above **works** in my local db. So, the only difference remaining is the `MongoDb Server version`:

- The one i'm using in the production project is `MongoDB 4.2.8 Enterprise`
- The one i'm using in my localhost is `MongoDB 5.0.3 Community`

Changing the server with the same code you provided produces the problem.

My apologies for not checking that, it didn't come to my mind. We will figure it out.

Thanks for the quick reply!
