### ISSUE TITLE
[Feature Request] Add property attribute to configure TTL

### ISSUE THREAD

**Issue by thepra** [dj-nitehawk/MongoDB.Entities#203]
It would make it easier if was supported by this useful library:
![immagine](https://user-images.githubusercontent.com/7032509/236367435-6e8b0140-6560-4398-8e48-8799c1104235.png)

**Comment by dj-nitehawk** [comment]
you can already create TTL indexes like this:
https://github.com/dj-nitehawk/VisitorLog/blob/9b6650ee12d222f039386dfd5921dde2a30754c6/VL-Api-Server/Source/Entities/EmailVerificationToken.cs#L14-L17
