### ISSUE TITLE
Question : Different ways of text searching

### ISSUE THREAD

**Issue by cloudb0x** [dj-nitehawk/MongoDB.Entities#21]
As per [https://docs.mongodb.com/manual/text-search/](Docs) one can do different searches using certain indicators in the query.

Is this something this library supports or the driver at all? 

For example `db.stores.find( { $text: { $search: "\"coffee shop\"" } } )`

Would return all matches that contain coffee shop.

**Comment by dj-nitehawk** [comment]
yes... please see the wiki [here](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/05.-Indexes#full-text-search) regarding it.
basically you do the following:
create index like this:
```csharp
DB.Index<Store>()
  .Key(s => s.Name, KeyType.Text)
  .Create();
```
and then do the text search like this:
```csharp
DB.SearchText<Store>("coffee shop");`
```
here's another example from the [test project](https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/Tests/TestIndexes.cs#L11).

**Comment by cloudb0x** [comment]
The behaviour I see is different.

When I perform  `var stores = DB.SearchText<Store>("coffee shop");`

All indexed fields that contain the word "coffee" and "shop" are returned/

For Example : 
`the shop`
`coffe place`

What im looking for is:
`coffee shop a`
`coffee shop b`

**Comment by dj-nitehawk** [comment]
ah, for that you have to enclose and escape within quotation marks like this:
`var shops = DB.SearchText<Store>("\"coffee shop\"");`

**Comment by cloudb0x** [comment]
OH ! Its literally that simple - I think it would be worth adding to the docs but I can see that you pass this to the driver to interpret anyway so maybe they should add it to theirs.

**Comment by cloudb0x** [comment]
I will try this and report back!

**Comment by cloudb0x** [comment]
@dj-nitehawk  this unfortunately did not work

**Comment by dj-nitehawk** [comment]
the following only returns `coffee shop a` and `coffee shop b` for me:
```csharp
using MongoDB.Entities;
using MongoDB.Entities.Core;

namespace TestApp
{
    public class Store : Entity
    {
        public string Name { get; set; }
    }

    public class Program
    {
        private static void Main(string[] args)
        {
            new DB("test", "localhost");

            (new[] {
                new Store { Name = "the shop"},
                new Store { Name = "coffee place"},
                new Store { Name = "coffee shop a"},
                new Store { Name = "coffee shop b"}
            }).Save();

            DB.Index<Store>()
              .Key(s => s.Name, KeyType.Text)
              .Option(o => o.Background = false)
              .Create();

            var shops = DB.SearchText<Store>("\"coffee shop\"");
        }
    }
}
```

**Comment by cloudb0x** [comment]
You are right - I misunderstood this usage.

What I was actually looking for was  ` var shops = DB.SearchText<Store>("\"coffe\"");`

Should return `coffee shop a` , `coffee shop b` , I guess what im looking for partial word search.

**Comment by dj-nitehawk** [comment]
for partial matching you can do this:
```csharp
            var shops = DB.Queryable<Store>()
                          .Where(s =>
                                 s.Name.Contains("coffe") &&
                                 s.Name.Contains("sho"))
                          .ToList();
```
but bear in mind mongodb uses regex matching for partial searches and might now utilize the index. so when searching millions of documents, partial matching may be slow.

**Comment by dj-nitehawk** [comment]
you might find [this article useful](https://medium.com/statuscode/how-to-speed-up-mongodb-regex-queries-by-a-factor-of-up-to-10-73995435c606) regarding text searches in mongodb.

**Comment by cloudb0x** [comment]
> for partial matching you can do this:
> 
> ```cs
>             var shops = DB.Queryable<Store>()
>                           .Where(s =>
>                                  s.Name.Contains("coffe") &&
>                                  s.Name.Contains("sho"))
>                           .ToList();
> ```
> 
> but bear in mind mongodb uses regex matching for partial searches and might not utilize the index. so when searching millions of documents, partial matching may be slow.

I was hoping to avoid doing this.

**Comment by dj-nitehawk** [comment]
> I apologize - this is no longer pertaining to your project
no worries at all...

well, the lack of fuzzy matching is a limitation of mongodb server. [mongodb atlas](https://www.mongodb.com/atlas/full-text-search) has a lucene engine which does this.

you could always use [lucene.net](https://lucenenet.apache.org/) yourself. haven't tried it yet personally.

**Comment by schorges** [comment]
i had a problem with fulltext search (textbox with keydown event and
search on all typed chars)

after long searching i found a solution, 
but this is a slow version. on 
DB.SearchText -< only case sensitve and the full word will search

my way:

   ```

 //regex ? not work will result all:
                //var list = DB.Find<MyTestItem>()
                //    .MatchExpression("{ '$regex':'"+searchtext+"', '$options' : 'i'} " )                
                //    .Execute();

var list = DB.Queryable<MyTestItem>()
                          .Where(s =>
                                 s.name.ToLower().Contains(searchtext) )                             
                          .ToList();
```
