### ISSUE TITLE
Nullable ID field in IEntity interface

### ISSUE THREAD

**Issue by m-sokol-esky** [dj-nitehawk/MongoDB.Entities#210]
I wanted to ask about the reasoning behind nullable ID field in the IEntity interface and why it was not introduced as a breaking change. It actually broke our codebase, including mappers, tests, etc.

Why would you ever want to have a null ID? Is there no better way to check whether it was already populated?

**Comment by dj-nitehawk** [comment]
it was introduced as a [breaking change](https://github.com/dj-nitehawk/MongoDB.Entities/releases/tag/v22.0.0).

[see here](https://github.com/dj-nitehawk/MongoDB.Entities/pull/194#issuecomment-1418522292) for the discussion we had regarding this.

that being said... i am finding having to the use the `!` everywhere (just to get rid of the green squiggly line) in my projects is a bit tedious and doesn't make much sense. so i'm thinking about making the `Entity.ID` non-nullable.

@dberry-rcs do you have any input on this?

**Comment by m-sokol-esky** [comment]
sorry, I thought it was introduced [here](https://github.com/dj-nitehawk/MongoDB.Entities/commit/2df963c5ee4850985bdf1a1bf0b5305d52f604da) (v22.1)

I agree, I had to add thousands of `!` to fix all the errors and I think it is not worth it, seeing that 99% of times it will not actually be null.

**Comment by dberry-rcs** [comment]
> it was introduced as a [breaking change](https://github.com/dj-nitehawk/MongoDB.Entities/releases/tag/v22.0.0).
> 
> [see here](https://github.com/dj-nitehawk/MongoDB.Entities/pull/194#issuecomment-1418522292) for the discussion we had regarding this.
> 
> that being said... i am finding having to the use the `!` everywhere (just to get rid of the green squiggly line) in my projects is a bit tedious and doesn't make much sense. so i'm thinking about making the `IEntity.ID` non-nullable.
> 
> @dberry-rcs do you have any input on this?

I am okay with this. I typical create the ID upfront and don't wait for it to be added by the framework. Changing it to not null will require that the checks to see if the object has been saved will need to change. The framework will no longer be able to assume that having an ID means it has been saved.

**Comment by dj-nitehawk** [comment]
completed in `v23` release
