### ISSUE TITLE
Disallow saving objects with unregistered discriminator value

### ISSUE THREAD

**Issue by BenStorey** [dj-nitehawk/MongoDB.Entities#212]
Hi,

I'm running into an annoying problem and haven't been able to find a solution online to this. I have a collection of classes that subclass MongoDB.Entities.Entity, and those all work fine. I've had a couple of problems though where either:

1. I've accidentally written a subclass of one of those classes to the DB, or
2. One of those classes has contained some other type (from another lib) and that got persisted accidentally

What then happens is that the write completes okay, things seem normal, but then when I restart my application - it dies because of the "unknown discriminator" value, as it sees the _t but doesn't know the object type because I haven't added a mapping. I feel like if the library knows I won't be able to read it back, then it shouldn't write it either.

Is there a way I can manually do this check in code before writing? Like serialise it to one format and then check to see if I can deserialise it back?

Is there a way to configure the library such that, if it throws the "unknown discriminator" error, that it just returns the values that it could parse, rather than return nothing at all? I also don't see from the logs how I'm supposed to identify which document(s) had that problem. Is there a hook somewhere that I can log from to find out?

Thanks!

**Comment by dj-nitehawk** [comment]
can you pls check if you get the same issue with the official driver?
if the issue is not replicable with the official driver, can you show me how to reproduce it so i can debug it.
a small repro console app would be ideal.
thanks!

**Comment by BenStorey** [comment]
Hi thanks for responding so fast,

I'd guess it's probably the same issue in the official driver. This problem came about at work and I don't have anything handy I can show you from home, so I thought I could explain through psuedocode:

```
class Base: MongoDB.Entities.Entity
{
    bool someProp {get; set;}
}

class Derived: Base
{
    bool somethingElse  {get; set;}
}

// save derived
var d = new Derived();
await DB.Save(d);

// Read everything. My process will have restarted between this line below and the ones above, but I doubt it matters?
await DB.Find<Base>().ExecuteAsync();
```

That last line should fail with an unknown descriminator, as the doc will have a "_t: Derived" value in it, but we haven't given it a Mapping for what "Derived" is. 

I'll do some more experimenting at work this week, maybe it's something I should raise to the official driver people instead.

**Comment by dj-nitehawk** [comment]
ah i see...
it's currently not supported to use base types to save/query using the library.
as of now, the concrete type must be used.
polymorphism is also kinda wonky in the official driver and can lead to weird situations if i remember correctly.
