### ISSUE TITLE
Does DB.Update lock row while update?

### ISSUE THREAD

**Issue by kingsanu** [dj-nitehawk/MongoDB.Entities#215]
I've 3 billing machin and they want latest stock from central database and that database habe only one row/document shared to 3 billing machine, so i want to ask does Db.Update() lock the row? if not than what can be other option, i seen findAndModify can help i think so how can i use then ?

**Comment by dj-nitehawk** [comment]
[this is how](https://mongodb-entities.com/wiki/Entities-Update.html#update-and-retrieve) you do a `findAndModify` in mongodb-entities.

[here's how](https://mongodb-entities.com/wiki/Entities-Update.html#update-and-retrieve) mongodb server handles concurrency, and the [atomicity of findAndModify](https://www.mongodb.com/docs/manual/core/write-operations-atomicity/#concurrency-control).

**Comment by kingsanu** [comment]
Dear sir, I understand that you have an option called UpdateAndGet. My inquiry is whether this option internally locks the row when another person is updating the same row. If it does, does another request wait until the first update is complete, or does it simply fail (the second request)?

**Comment by dj-nitehawk** [comment]
the library does nothing special regarding locking and ultimately delegates the call out to the mongo driver's `FindOneAndUpdateAsync()` method:

https://github.com/dj-nitehawk/MongoDB.Entities/blob/4746012d66d5b2132020d354d757b3bd50681b76/MongoDB.Entities/Builders/UpdateAndGet.cs#L471
