### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'MongoDB.Entities.Cache`1' threw an exception

### ISSUE THREAD

**Issue by jushstone** [dj-nitehawk/MongoDB.Entities#219]
I recently upgraded my .NET core web-api project from version 6 to 8 and also updated its packages. But the MongoDB entities package (v23.1.0) has encountered a problem and gives the following error. Also, I use MongoDB driver package (v2.24.0). This error occurs in the following two methods. How should I fix this error in this current version?

Error:

> System.TypeInitializationException: The type initializer for 'MongoDB.Entities.Cache`1' threw an exception.

** Method 1:

```
public async Task<List<Post>> GetAllPostsWithPublisher(string? queryString)
{
    _ = new List<Post>();
    List<Post> posts;

    if (queryString == null)
    {
        posts = await DB.Find<Post>().ExecuteAsync();
    }
    else
    {
        IMongoQueryable<Post> query = DB.Collection<Post>().AsQueryable();
        var features = new APIFeatures<Post>(query, queryString);
        posts = await features.Filter().Sort().Paginate().ToListAsync();
    }

    foreach (var post in posts)
    {
        var publisher = await DB.Find<User>().OneAsync(post.PublisherId.ToString());
        post.Publisher = publisher;
    }

    return posts;
}
```

** Method 2:

```
public Task<User?> GetUserByIdWithRelations(string userId)
{
    return Task.Run(async () =>
    {
        var user = await FindById(userId);

        if (user == null)
        {
            return null;
        }

        user!.Wishlist = await DB.Find<Wishlist>()
            .Match(p => p.UserId == userId)
            .ExecuteAsync();

        foreach (var wishlist in user.Wishlist)
        {
            wishlist.Product = await DB.Find<Product>()
                .Match(p => p.ID == wishlist.ProductId)
                .ExecuteFirstAsync();
        }

        user!.Bag = await DB.Find<Card>()
            .Match(p => p.UserId == userId)
            .ExecuteAsync();

        foreach (var card in user.Bag)
        {
            card.Product = await DB.Find<Product>()
                .Match(p => p.ID == card.ProductId)
                .ExecuteFirstAsync();
        }

        return user;
    });
}
```

**Comment by dj-nitehawk** [comment]
the info you've given is not sufficient to figure out why it's throwing. 

show me how to reproduce it in a minimalistic, standalone manner pls. 

could you attach a small repro project?

thanks!

**Comment by jushstone** [comment]
As long as I can make a sample, I have to say that the following versions do not have any problems for MongoDB packages with .NET 8. I used these versions of the packages along with the updated .NET packages and the project was executed without any problems.

<PackageReference Include="MongoDB.Bson" Version="2.19.1" />
<PackageReference Include="MongoDB.Driver" Version="2.19.1" />
<PackageReference Include="MongoDB.Entities" Version="21.0.2.6-beta" />

**Comment by dj-nitehawk** [comment]
there has been some [breaking changes](https://github.com/dj-nitehawk/MongoDB.Entities/releases) since that version.
in order to understand which of those breaking changes is affecting your code, i'll need to know exactly how to replicate it.
without a repro, it's a guessing game which isn't going to help anyone :-)

**Comment by dj-nitehawk** [comment]
maybe try incrementally upgrade from that version and see at which version it starts to break first.
have a look at the released notes for that release and see if can spot what code needs to change in order to support it.

**Comment by jushstone** [comment]
OK. I checked now and from version 23.0.0, which we had breaking change for Many<> and IEntity, my project is having problems. I also checked the code and the only places I used were the following, so I have to drink a lot of coffee to find the problem :).

```
await DB.Collection<T>().DeleteManyAsync(filter);
public class Repository<T> : IRepository<T> where T : class, IEntity
```

**Comment by dj-nitehawk** [comment]
DeleteManyAsync is a vanilla driver method and not something offered by this library. 

when you do DB.Collection<T>, your directly accessing the IMongoCollection of the official driver.

**Comment by jushstone** [comment]
Now, I understood that the problem is the inheritance from the Entity class, which itself inherits from the IEntity interface. According to the breaking changes, two methods, GenerateNewID() and HasDefaultID(), should be implemented. Then for my case which is below, how should I do this?

```
public class User : Entity
{
    [Ignore]
    public string _id
    {
        get
        {
            return ID.ToString();
        }
    }
```

**Comment by dj-nitehawk** [comment]
try this:
```cs
public class User : Entity
{
    [Ignore]
    public string _id
    {
        get => ID;
        set => ID = value;
    }
}
```

**Comment by jushstone** [comment]
Yes, thanks, it is now working.
