### ISSUE TITLE
DB.UpdateAndGet() + "Insert an entity if it doesn't exist"

### ISSUE THREAD

**Issue by pachanga** [dj-nitehawk/MongoDB.Entities#220]
Hi! 

I was wondering whether it's possible _to update and get an entity_ **or** _insert and retrieve it_ using one API call, so that it happens atomically on Mongo level?

Something as follows:

```cs
var book = await DB.UpdateAndGet<Book>()
    .Match(b => b.ID == "xxxxxxxxxxxxx")
    .Modify(b => b.Title, "updated title")
    .ModifyOnInsert(b  => b.Author, "Bob") // this part is executed only if entity doesn't exist and it's inserted
     .ModifyOnInsert(b  => b.Links, 1) // this part is executed only if entity doesn't exist and it's inserted
    .ExecuteAsync(); 
```

**Comment by dj-nitehawk** [comment]
you can do an upsert as shown here: https://github.com/dj-nitehawk/MongoDB.Entities/issues/216#issuecomment-1868503265
but i don't think the mongo driver can do different things depending on whether its an update or insert.
i.e. if you upsert, the document/entity will have both `author` set to `bob` & `links` set to `1` in both cases.
