### ISSUE TITLE
PagedSearch search big data is very slow

### ISSUE THREAD

**Issue by uServe-UP** [dj-nitehawk/MongoDB.Entities#221]
I have 8573059 data. and I try to use 
				var re = await DB.PagedSearch<Orders>()
					.Sort(b => b.OrderId,Order.Descending)
					.PageSize(10)
				  .ExecuteAsync();

It takes 00:00:19.7464839 

when I use Find function skip(10) and limit(10)  it take 00:00:00.1045675.

If I want use PagedSearch. what should I do?

**Comment by uServe-UP** [comment]
how long does it take if you do PagedSearch without the Sort?  Will get an error "Paging without sorting is a sin!"
does the situation improve if you index the OrderId field?  "I have  index on the OrderId field"

I will try your suggest Thank you

**Comment by dj-nitehawk** [comment]
also try the `find` query with the same sort and see if the time increases.

**Comment by dj-nitehawk** [comment]
this is basically what the pagedsearch method generates: https://stackoverflow.com/a/48307554

try profiling to get the actual generated query and run it in the db. see if there's any clues there for the slowdown.
