### ISSUE TITLE
System.InvalidCastException in ToReference()

### ISSUE THREAD

**Issue by CodeyDotNet** [dj-nitehawk/MongoDB.Entities#223]
Hello,

i have a ClassA with a Property of Type `One<ClassB>`. When i try to set the Property with `obj.ToReference()`, i got a 

> System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.String'.
>    at MongoDB.Entities.One'1..ctor(TEntity entity)
>    at MongoDB.Entities.Extensions.ToReference[T](T entity)

The Id of ClassB is type of long.

Is this a bug or did i something wrong?

Greetings
Mike

**Comment by dj-nitehawk** [comment]
looks like we forgot to document it but you have to use `One<TEntity, TIdentity>` generic overload when using custom ID formats.

**Comment by CodeyDotNet** [comment]
Thanks for the hint. I changed that, but now i've got the next error:

> Cannot implicitly convert type "MongoDB.Entities.One<ClassB>" to "MongoDB.Entities.One<ClassB, int>".

**Comment by dj-nitehawk** [comment]
the `ToReference()` extension for `One<T,TId>` is currently missing. will add it soon.
you can do the following for the time being:

https://github.com/dj-nitehawk/MongoDB.Entities/blob/33310634764480f5ae83f3a9d8214963f6f99a4b/Tests/Int64Tests/TestRelationships.cs#L21

**Comment by dj-nitehawk** [comment]
so...
it looks like we don't have a `ToReference()` method on the `One<T,TId>` type because it would have to be called like so:

```cs
objA.ClassB = objB.ToReference<ClassA,long>()
```

which is more verbose than just doing:

```cs
objA.ClassB = new(objB)
```
