### ISSUE TITLE
Storing different objects (of different types) with a common base object in single table

### ISSUE THREAD

**Issue by ssteiner** [dj-nitehawk/MongoDB.Entities#224]
Besides having a considerable number of well defined entities, I have one entity where I only know the base structure. 

```
public class BaseEntity: Entity
{
  public string Name {get; set;}
.. other common attributes here
}
```

The actual entities to store would derive from `BaseEntity` - but instead of getting the typed object, I'm getting a JSON document. Is there a way to handle with with MongoDB.Entites other than declaring an additional string prop that holds the json? In the official MongoDb driver I'm using a table of `BsonDocument` which allows for that, but MongoDB.Entities seems much more suited for the rest of what I'm doing.

**Comment by dj-nitehawk** [comment]
that is currently not supported.
see #95 
you can always use the official driver for scenarios that are not supported by this library.
