### ISSUE TITLE
Not compatible with MongoDB driver version 2.28

### ISSUE THREAD

**Issue by natesitton80** [dj-nitehawk/MongoDB.Entities#226]
Tried to update my code to use MongoBD driver 2.28 but get errors everywhere I am using MongoDB Entities due to Entities using MongoDB driver 2.24. This is probably due to driver 2.28 strong naming their assemblies now.
Will this package be updated anytime soon to use MongoDB driver 2.28?

**Comment by dj-nitehawk** [comment]
done...
grab the latest release from nuget.
