### ISSUE TITLE
Index creation problem with version 23.1.1 in .net 8

### ISSUE THREAD

**Issue by huseyingoztok** [dj-nitehawk/MongoDB.Entities#227]
Hello,

I'm having trouble creating indexes in .NET Core 8. I’m providing a sample code below. What could be the reason why the indexes are not being created?

await DB.Index<X>()
                .Key(x => x.A, KeyType.Text)
                .Key(x => x.B, KeyType.Text)
                .Key(x => x.C, KeyType.Text)
                .CreateAsync();
                
Best regards.

**Comment by huseyingoztok** [comment]
Actually, I'm trying it the way you suggested, but the indexes are not being created.

`await DB.Index<Item>()
                .Key(x => x.Make, KeyType.Text)
                .Key(x => x.Model, KeyType.Text)
                .Key(x => x.Color, KeyType.Text)
                .CreateAsync();`

**Comment by dj-nitehawk** [comment]
@huseyingoztok can you attach a small repro project pls? index creation works fine last i checked.
