### ISSUE TITLE
Is it possible to use a other type than string for the Id?

### ISSUE THREAD

**Issue by atresnjo** [dj-nitehawk/MongoDB.Entities#23]
Hey, thanks for the library! Saved me a lot of time. It is possible to use a different type for the Id? Right now I'm saving it in another field, but that's just a waste of space obviously.

Thanks! :)

**Comment by dj-nitehawk** [comment]
glad to be of service!
what type would you like to use?
i'll look in to what can be done about this requirement.

**Comment by atresnjo** [comment]
> 
> 
> glad to be of service!
> what type would you like to use?
> i'll look in to what can be done about this requirement.

Guid would be really nice, thanks!

**Comment by dj-nitehawk** [comment]
ill look in to it within the next couple of days. 
in the meantime have a look at [this](https://github.com/Restuta/mongo.Guid-vs-ObjectId-performance#mongoguid-vs-objectid-performance)

also, may i know why you'd like to use guids instead of objectids? just curious :-)

**Comment by dj-nitehawk** [comment]
the following is possible without any changes to the library:
create your own guid based entity base class by implementing `IEntity` interface
```csharp
    [BsonIgnoreExtraElements]
    public abstract class MyEntity : IEntity
    {
        [BsonId(IdGenerator = typeof(GuidGenerator))]
        public string ID { get; set; }

        public DateTime ModifiedOn { get; set; }     
    }
```
create and save your entities like this:
```csharp
    public class Person : MyEntity
    {
        public string Name { get; set; }        
    }

    (new Person
    {
        ID = Guid.NewGuid().ToString(),
        Name = "john doe"
    }).Save();
```

would that do it for you?

**Comment by atresnjo** [comment]
> 
> 
> ill look in to it within the next couple of days.
> in the meantime have a look at [this](https://github.com/Restuta/mongo.Guid-vs-ObjectId-performance#mongoguid-vs-objectid-performance) and [this](https://stackoverflow.com/questions/11355792/with-mongodb-and-guids-for-the-id-of-documents-what-is-efficient-way-to-store-the-guids-to-easily-retrieve-the-actual-guid)
> 
> also, may i know why you'd like to use guids instead of objectids? just curious :-)

Thanks for the help. I'll try your suggestion!

To answer your question: I am dealing with data from various sources and they want to access it with their own Guid. So the current ID as string is redundant for me, as they will be always searching with their own identifier.

**Comment by dj-nitehawk** [comment]
with the above approach everything else will work other than the built-in referenced relationships. if you don't mind managing referenced entities yourself, it'll work fine.

**Comment by atresnjo** [comment]
> 
> 
> with the above approach everything else will work other than the built-in referenced relationships. if you don't mind managing referenced entities yourself, it'll work fine.

Okay, sadly I am using the built-in referenced relationships. But for now it works fast enough with the Id as string, so my change doesn't have that high priority. Thanks!

**Comment by dj-nitehawk** [comment]
just add an ascending or descending index for your guid field and searches on that field will be as fast as the ID field.

**Comment by LucaZiegler** [comment]
Is it possible to use MongoDB.Bson.ObjectId?

**Comment by dj-nitehawk** [comment]
@LucaZiegler sorry the default ID type is not customizable. but the value is stored in mongodb as ObjectId. string was chosen to shield application logic from mongodb related stuff.
