### ISSUE TITLE
return zero

### ISSUE THREAD

**Issue by kingsanu** [dj-nitehawk/MongoDB.Entities#234]
i trying to filter only date except time, but it return me 0

    var orders2 = DB.Queryable<MongoOrders>().Where(x => x.DateTill12AM.Date == parsedDate.Date).ToList();

**Comment by dj-nitehawk** [comment]
mongo server doesn't support equality comparison on just the date component of a stored utc isodate.
so have to do a range query something like the following:
```cs
var results = await DB.Find<MyDocument>()
                      .Match(doc => doc.MyDate >= startOfDay && doc.MyDate < endOfDay)
                      .ExecuteAsync();
```

**Comment by dj-nitehawk** [comment]
that is the default behavior of the mongodb server and the official driver and not something related to this library. besides, the best approach to future proof your app is to store dates in utc and convert to and from required time zones with your app code. most of the time, i use the nodatime library.
