### ISSUE TITLE
Unable to connect remote connection string

### ISSUE THREAD

**Issue by arifjmamun** [dj-nitehawk/MongoDB.Entities#24]
The documentation just only shows the local environment setup.
Please provide a implementation of remote connection string with example.
_Ex: mongodb+srv://<username>:<password>@bc-aymj0.gcp.mongodb.net/test_mongo_

**Comment by dj-nitehawk** [comment]
sorry i'll update the docs.
first import this:
```csharp
    using MongoDB.Driver;
```
then connect like this:
```csharp
    var settings = MongoClientSettings
        .FromConnectionString("mongodb+srv://dbuser:dbpassword@cluster0-vldv8.gcp.mongodb.net/test?retryWrites=true&w=majority");

    new DB(settings, "test");
```

**Comment by arifjmamun** [comment]
A lot of thanks for your information.
