### ISSUE TITLE
Documentation: Async Overloads

### ISSUE THREAD

**Issue by Log234** [dj-nitehawk/MongoDB.Entities#27]
The documentation states that there are async overloads for all provided methods and extensions.
https://github.com/dj-nitehawk/MongoDB.Entities/wiki/07.-Async-Support
But in the DB class, only Save and Delete appears to have one.

In my application I wanted to use an async Find, but was unable to find the overload.
I will suggest either clarifying the documentation or adding overloads for methods such as Find,

Thank you for an otherwise great library!

**Comment by Log234** [comment]
I just realised the overload was on One, rather than Find!
To use Find async, do DB.Find<Note>().OneAsync("id");

Perhaps clarifying this in the documentation would be good regardless.

**Comment by dj-nitehawk** [comment]
i'll look in to improving the documentation.
also DB.Find().ExecuteAsync() is there if you wanna build queries instead of .OneAsync() or .ManyAsync()
