### ISSUE TITLE
Updating entities with aggregation pipeline stages with C# array/objects

### ISSUE THREAD

**Issue by arifjmamun** [dj-nitehawk/MongoDB.Entities#29]
Is there any way to use pipeline stages to updating entities with C# object or array?

**Comment by dj-nitehawk** [comment]
have you seen the documentation here: 
https://github.com/dj-nitehawk/MongoDB.Entities/wiki/02.-Entities#updating-entities-with-aggregation-pipeline-stages

**Comment by dj-nitehawk** [comment]
you might also be interested in this new feature:
https://github.com/dj-nitehawk/MongoDB.Entities/wiki/13.-String-Templates
