### ISSUE TITLE
References are ophaned when deleting the parent document

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#3]
I just noticed that when having these **`Many<T>`** properties on the entity class, when deleting the parent entity, there are orphaned records on the collection named [(x)parent~child(x)].

**Comment by dj-nitehawk** [comment]
yeah it seems like you missed a spot with the PR. it should be fixed now with the v4.3 release. could you please check with 4.3 and report back if the problem still persists?
thanks!

ps: please use the dev branch for making PRs in the future. thanks!

**Comment by paolobriones** [comment]
ok, noted... sorry about that, i didnt notice the dev branch last night; will report back my findings

**Comment by paolobriones** [comment]
Testing looks good, this is no longer an issue
