### ISSUE TITLE
Expose IMongoDatabase thru the DB object

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#32]
I'm finally trying to integrate GridFS file handling through the API and need to get access to the underlying IMongoDatabase instance to create an IGridFSBucket object. 

Since the API supports multiple DB instances and internally manages this list, maybe the fix is to make the DB.GetDB() method as public, what do you think?

Thanks again @dj-nitehawk

**Comment by paolobriones** [comment]
Since GridFS is pretty straight forward, it might not be necessary to add additional logic to the MongoDB.Entities API for this; by exposing the IMongoDatabase, we can just use the vanilla GridFS code from the Mongo Driver.

**Comment by dj-nitehawk** [comment]
i'll make GetDB public. i'm about to release the next version in less than an hour.

is there any reason why you chose to use GridFSBucket instead of [this](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/12.-File-Storage)? is some feature missing from the library file storage system?

**Comment by paolobriones** [comment]
oh wow, i didnt even see this feature the last time i opened the wiki; cancel my request, ill use your approach! awesome!!

**Comment by dj-nitehawk** [comment]
all good mate!
IMongoDatabase is now exposed via `DB.GetDatabase()` in any case...
