### ISSUE TITLE
How to write concurrent integration tests with multiple databases?

### ISSUE THREAD

**Issue by atresnjo** [dj-nitehawk/MongoDB.Entities#34]
Heya. I'm using XUnit and I'm trying to write integration tests using your library. The issue right now that I am having is, is that I have no control over which Database is being used when calling AddAsync on a Many collection. The relationship tables are created in a different database than the actual entities.

```cs
        [Fact]
        public async Task Must_Fail()
        {
            var dbNameWithRelationships = "db_name_with_relationships";
            var dbNameWithoutRelationships = "db_name_without_relationships";

            var dbWithout = new DB(dbNameWithoutRelationships);
            var dbWith = new DB(dbNameWithRelationships);

            var planToday = new SchoolPlanModel();
            await dbWith.SaveAsync(planToday);

            var school = new SchoolModel();
            await dbWith.SaveAsync(school);
            await school.Plans.AddAsync(planToday);
            planToday.School = school;
            await dbWith.SaveAsync(planToday);
        }
```

Results in:

![grafik](https://user-images.githubusercontent.com/41112852/77320292-97afb300-6d10-11ea-835f-9dfc745c8fea.png)

**Comment by dj-nitehawk** [comment]
did you remember to decorate the entities with the `DatabaseAttribute`? i just ran the following code and it created the relationship collection in the correct database.
```csharp
using MongoDB.Entities;
using MongoDB.Entities.Core;
using System.Threading.Tasks;

namespace Test
{
    [Database("db_name_with_relationships")]
    public class SchoolPlanModel : Entity
    {
        public One<SchoolModel> School { get; set; }
    }

    [Database("db_name_with_relationships")]
    public class SchoolModel : Entity
    {
        public Many<SchoolPlanModel> Plans { get; set; }

        public SchoolModel() => this.InitOneToMany(() => Plans);
    }

    public static class Program
    {
        private static async Task Main()
        {
            var dbNameWithRelationships = "db_name_with_relationships";
            var dbNameWithoutRelationships = "db_name_without_relationships";

            var dbWithout = new DB(dbNameWithoutRelationships);
            var dbWith = new DB(dbNameWithRelationships);

            var planToday = new SchoolPlanModel();
            await dbWith.SaveAsync(planToday);

            var school = new SchoolModel();
            await dbWith.SaveAsync(school);
            await school.Plans.AddAsync(planToday);
            planToday.School = school;
            await dbWith.SaveAsync(planToday);
        }
    }
}
```
also remember you cannot have cross-database relationships. all entities referenced by One\<T> and Many\<T> relationships must be attached to the same db. hope that clears it out. if you don't decorate an entity with the attribute, it is assumed it is to be saved in the default database. the default database is whatever DB instance your app creates first.

![mongo](https://user-images.githubusercontent.com/7043768/77340637-98b60400-6d53-11ea-8099-ff9566828db6.png)

**Comment by atresnjo** [comment]
The issue is that I'm creating the databases ad-hoc for every test because each test needs a fresh db. That's why I can't use the attribute. But yeah, my goal isn't to have cross-database relationships, but clean databases for every test.

**Comment by dj-nitehawk** [comment]
multi database support only works with the use of the attribute. so if your app uses multiple dbs to store entities you must specify which db to store an entity using the attribute unless it is to be stored in the default db. 

if your app can satisfy this requirement, you can write integration tests for your app logic without needing to create multiple dbs adhoc within every test. 

have a look at the integration test projects for this library as well as the 'mongo web api starter template' project under my github account and you will see what I mean.

**Comment by atresnjo** [comment]
Thanks for the help. I got it working by dropping the collections on every run and disabling concurrent execution of tests.
