### ISSUE TITLE
Fluent mapping.

### ISSUE THREAD

**Issue by MrFoxPro** [dj-nitehawk/MongoDB.Entities#35]
Hey. Great project! I would like to know, is it possible to map entities through fluent style? I want to use my models in shared library, so there any restriction on using inheritance in shared code. 
Thanks in advance.

**Comment by dj-nitehawk** [comment]
do you mean you want to create a library/project that only contains entity models? if so, the answer is yes. your models project will have a dependency on `MongoDB.Entities.Core.dll` and you can create inherited entities like this:
```csharp
using MongoDB.Entities.Core;

namespace EntityModels
{
    public class Animal : Entity
    {
        public string Species { get; set; }
    }

    public class Cat : Animal
    {
        public int NumOfLegs { get; set; }
    }
}
```
hope this answers your question. if not, please explain your requirement a bit further with an example.
