### ISSUE TITLE
help with one-To-many relationship

### ISSUE THREAD

**Issue by liodali** [dj-nitehawk/MongoDB.Entities#36]
i have objet  A that contain list of objet B 
why when i get A , attr B contain  JoinCollection { .... } not the real data that i created  ?

**Comment by dj-nitehawk** [comment]
have a look at this [gist](https://gist.github.com/dj-nitehawk/9971a57062f32fac8e7597a889d47714). it will give you an idea of how to use linked relationships. if something is unclear, pls let me know. thanks!
