### ISSUE TITLE
MongoDB.Entities.Many<TChild> should implement IEnumerable<T>

### ISSUE THREAD

**Issue by Maximys** [dj-nitehawk/MongoDB.Entities#38]
Will be very useful if relationship [Many](https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/MongoDB.Entities/Relationships/Many.cs) implement IEnumerable<T>.

**Comment by Maximys** [comment]
PR with this changes: https://github.com/dj-nitehawk/MongoDB.Entities/pull/37

**Comment by dj-nitehawk** [comment]
thanks for the PR... it has been merged to dev branch. will release with the next version soon.
