### ISSUE TITLE
A problem with mapping relational entities with AutoMapper

### ISSUE THREAD

**Issue by MohamedAarab** [dj-nitehawk/MongoDB.Entities#40]
I'm trying to map a relational property to a normal entity, however I can't figure out how to go on about this. I have an entity class and a DTO class, let's take Product for example.

Product.cs: 
`public One<Discount> Discount`

ProductResponse.cs:
`public Discount Discount`

Now AutoMapper doesn't know how to map this because these two objects have different class types, so I want to configure every property with the type One<TEntity> to convert it using .toEntity().

So if Product were to be automapped by AutoMapper it would convert One<Discount> to Discount using .toEntity(). Is there any way to achieve this?

**Comment by dj-nitehawk** [comment]
yes, `ToEntity()` would be the easy way to fetch a related/referenced entity. however that would issue a separate db query.

you can do an aggregation pipeline with a lookup stage to get back the desired output/dto with a single query like so:

```csharp
using MongoDB.Driver;
using MongoDB.Entities;
using MongoDB.Entities.Core;
using System.Linq;

namespace TestApp
{
    public class Product : Entity
    {
        public string Name { get; set; }
        public One<Discount> Discount { get; set; }
    }

    public class Discount : Entity
    {
        public int Rate { get; set; }
    }

    public class ProductResponse
    {
        public string Name { get; set; }
        public Discount Discount { get; set; }
    }

    public static class Program
    {
        private static void Main()
        {
            new DB("test");

            var discount = new Discount { Rate = 10 };
            discount.Save();

            new Product
            {
                Name = "hammer",
                Discount = discount
            }.Save();

            var response = DB.Fluent<Product>()
                             .Match(p => p.Name == "hammer")
                             .Lookup<Product, Discount, ProductResponse>(
                                DB.Collection<Discount>(),
                                p => p.Discount.ID,
                                d => d.ID,
                                r => r.Discount)
                             .AppendStage<ProductResponse>("{$set:{Discount:{$arrayElemAt:['$Discount',0]}}}")
                             .ToList();
        }
    }
}
```

**Comment by dj-nitehawk** [comment]
btw, i discourage people from using automapper. here's a couple of articles describing why:
1. https://cezarypiatek.github.io/post/why-i-dont-use-automapper/
2. https://sietch.net/ViewNewsItem.aspx?NewsItemID=260
3. http://davecallan.com/automapper-doesnt-save-time/
