### ISSUE TITLE
Many<T> entities don't show up on Mongo Atlas

### ISSUE THREAD

**Issue by adrenak** [dj-nitehawk/MongoDB.Entities#41]
Thanks for the excellent project. I'm using this with mongo atlas and tried out the example Program.cs

While everything is working great, objects being added using `Many<T>.Add` such as  [here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/d85b8479afb2580efaa45aa2ce222104ffa523a7/Examples/Program.cs#L68) are not showing up on the web dashboard. It IS being stored though because I can retrieve them.

**Comment by adrenak** [comment]
I've also tried in dbKoda and it's the same there

**Comment by dj-nitehawk** [comment]
when it comes to referenced relationships, there are 3 collections in concern: 

parent collection + join collection + child collection

are you saying that they join collection is not shown in atlas? 

I haven't tried atlas myself but there shouldn't be any issues. I'm away from a computer right now I'll trial out atlas when I get a chance. 

in the meantime please see the "schema changes" section of the wiki to understand how referenced relationships work.

**Comment by adrenak** [comment]
Oh I see, it shows up in `[Book~Author(Authors)]` Didn't realize how it works at first but it makes sense now. Thanks!
