### ISSUE TITLE
Lookup/Join on One-To-Many relationship

### ISSUE THREAD

**Issue by ovaiss** [dj-nitehawk/MongoDB.Entities#43]
In the given example i.e.

There is 1 to many relationship between book and authors.
how I can get all the authors and their books in one object?

**Comment by dj-nitehawk** [comment]
i believe this [gist](https://gist.github.com/dj-nitehawk/9971a57062f32fac8e7597a889d47714) would answer your question.

in the gist, it is getting one author with all of his books. to retrieve all authors with their books, simply change the `.Match(a => a.ID == author.ID)` to `.Match(_ => true)`
