### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by rickavmaniac** [dj-nitehawk/MongoDB.Entities#44]
HI,

Seem not compatible with Blazor (server). I try ASP.NET WEbApp and everything is fine but with Blazor can save but cannot do any Find()

Anything I am missing or it's just not ready for Blazor ?

**Comment by dj-nitehawk** [comment]
there's no issue using with blazor. check the sample blazor project below inside weather service and startup class.

[BlazorApp1.zip](https://github.com/dj-nitehawk/MongoDB.Entities/files/4607510/BlazorApp1.zip)

**Comment by rickavmaniac** [comment]
Thanks ok half way there. It wok in Blazor but only with a Find()

If I do a .Save() and after a Match() in the same module. The find() dont execute.

If I comment the save() then the Match work as expected.

Code exemple : 
** Match() dont execute not ok **
public void OnClickButton()
    {

        Person p = new Person { FirstName = "Eric", LastName = "Lacoste" };
        p.Save();

        myList = DB.Find<Person>().Match(p => p.FirstName == "Eric").Execute().FirstOrDefault();
    }

Code exemple : 
** Match() execute ok because I comment the save()**
public void OnClickButton()
    {

        //Person p = new Person { FirstName = "Eric", LastName = "Lacoste" };
        //p.Save();

        myList = DB.Find<Person>().Match(p => p.FirstName == "Eric").Execute().FirstOrDefault();
    }

**Comment by dj-nitehawk** [comment]
i just ran the following test and it works fine. if zip up the blazor project and attach here, i can have a look for ya.
```csharp
using MongoDB.Entities;
using MongoDB.Entities.Core;
using System;
using System.Linq;

namespace TestApp
{
    public static class Program
    {
        public class Person : Entity
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        private static void Main()
        {
            new DB("TestDB", "localhost");

            Person p = new Person
            {
                FirstName = "Eric",
                LastName = "Lacoste"
            };
            p.Save();

            var myPerson = DB.Find<Person>()
                             .Match(p => p.FirstName == "Eric")
                             .Execute()
                             .FirstOrDefault();

            Console.WriteLine(myPerson.FirstName + " " + myPerson.LastName);
            Console.Read();
        }
    }
}
```

**Comment by rickavmaniac** [comment]
Ok found it. I absolutely need to use ExecuteAsync() instead of Execute(). 

Execute() dont work if use after the save(). But do work if I dont use the save() before. Dont understand why but glad I find a way around. Anyway I prefer to use Async



By the way I really enjoy your library. It's well done, well think and so easy to use. 

Will use it starting from now. Great work !

**Comment by dj-nitehawk** [comment]
here's the async version. you must use async methods and await the result.
```csharp
using MongoDB.Entities;
using MongoDB.Entities.Core;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace TestApp
{
    public static class Program
    {
        public class Person : Entity
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        private static async Task Main()
        {
            new DB("TestDB", "localhost");

            Person p = new Person
            {
                FirstName = "Erica",
                LastName = "Lacoste"
            };
            await p.SaveAsync();

            var myPerson = (await DB.Find<Person>()
                             .Match(p => p.FirstName == "Erica")
                             .ExecuteAsync())
                             .FirstOrDefault();

            Console.WriteLine(myPerson.FirstName + " " + myPerson.LastName);
            Console.Read();
        }
    }
}
```
