### ISSUE TITLE
ToDocument() should set ID to null

### ISSUE THREAD

**Issue by Suplanus** [dj-nitehawk/MongoDB.Entities#47]
I want to copy an entity with `ToDocument()`.
After that I save it to DB. The _ObjectID_ is `000000000000000000000000`.

Workaround:  
Set the ID to null. I think this should be default.

![image](https://user-images.githubusercontent.com/2002916/81948654-40d4a480-9602-11ea-9123-d475676a842e.png)

**Comment by dj-nitehawk** [comment]
done...
new version released.
thanks for suggestion.

**Comment by Suplanus** [comment]
Thanks 💕
