### ISSUE TITLE
Support for saving files thru GridFS

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#5]
Although uploading files to databases are frowned upon, there are instances where this is still needed.

For example, in your KiwilinkCRM system, I would imagine contract or service documents (pdf or any other format) must be available to users of the system for quick reference.

@dj-nitehawk Awesome work! New features are working really well!

**Comment by dj-nitehawk** [comment]
thanks!
glad to hear you're liking it...
i'm not familiar with gridfs yet. will look in to it soon.
btw, if you decide to work on a PR for any new features, pls update me before starting work so there won't be any duplication of effort :-)

**Comment by dj-nitehawk** [comment]
still haven't had a chance to have a look at gridFS yet.
mostly because all files i've had to store in mongodb so far has been less than 16mb in size and there was no need to use gridFS specifically.
i'll close this for now and re-open when i can work on it at a later time...

**Comment by dj-nitehawk** [comment]
not sure if you're still using this library but thought you'd be interested to know.
i implemented a simpler solution than GridFS for storing files. have a look at the walkthrough [here](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/12.-File-Storage)

**Comment by paolobriones** [comment]
Looks good, will try this out later today! Awesome work!

**Comment by dj-nitehawk** [comment]
@paolobriones you're most welcome... glad to here it's been useful...

**Comment by paolobriones** [comment]
@dj-nitehawk thanks again! once I get my project off the ground, let's talk about us sponsoring your work. Your work is a critical component of my project :)

**Comment by dj-nitehawk** [comment]
great... in any case, i'd love to hear about your project sometime.
if you'd like to talk privately you can initiate it through [this link](https://changemon.com/#/contact-us)

**Comment by paolobriones** [comment]
@dj-nitehawk sent you a message thru your link
