### ISSUE TITLE
Example isn't compiling

### ISSUE THREAD

**Issue by renato04** [dj-nitehawk/MongoDB.Entities#53]
Hello,

I'm trying to use the `Program.cs` as a reference but it isn't compiling.

![image](https://user-images.githubusercontent.com/5497267/85726873-e6346b00-b6cc-11ea-9fec-71adfac9c466.png)

![image](https://user-images.githubusercontent.com/5497267/85727129-25fb5280-b6cd-11ea-976e-51c7f96c45f1.png)

It says there is an ambiguous call.

Am I missing something?

Thank you!

**Comment by dj-nitehawk** [comment]
i can't seem to reproduce this on my environment.
can you let me know the details of your environment like OS/IDE/.net framework version/etc.
if you look at the source code [here](https://github.com/dj-nitehawk/MongoDB.Entities/blob/master/MongoDB.Entities/DB.Queryable.cs#L15) you can see that one method is static and the other method is instance. 
when you do DB.Queryable<T>() it is specifically calling the static method.
something must be off in your environment.

**Comment by dj-nitehawk** [comment]
does the problem go away if you do this: `DB.Queryable<Author>(null)`

**Comment by renato04** [comment]
I'm using Windows 10, .net core 2.1, VS2017.

Yes, but I have to put two null values as parameters.

`DB.Queryable<Author>(null, null) `

It worked but it feels strange for me.

**Comment by dj-nitehawk** [comment]
i think you can fix this issue by updating to the latest SDK from [here](https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.301-windows-x64-installer).

you can still use vs2017 and target `netcoreapp2.0`. basically nothing else in needs to change other than installing the latest SDK bits.

let me know if that works.

**Comment by dj-nitehawk** [comment]
looks like this is a problem with vs2017 and the old .net core SDKs.
so i guess you'll have to either upgrade to vs2019 or use the following form:
```csharp
var db = new DB("dbname");
var res = db.Queryable<Author>()
```
the static DB.* methods will not be available to you unfortunately.

**Comment by renato04** [comment]
I can't update to  .net core 3.1 or VS because my company doesn't have the licenses.

Thank you!
