### ISSUE TITLE
Support for MongoDB Clusters

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#6]
Currently, we only specify a single server to connect to and the API needs to start supporting clustered MongoDB instances

**Comment by dj-nitehawk** [comment]
yes i will work on this next...
btw, just out of curiosity... how did u find this library? through stackoverflow, reddit or github search?

**Comment by paolobriones** [comment]
Thru RepoStumble... I was just browsing thru MongoDB related repositories and found your repo to work really well in .NET Core and was very easy to use. Now starting to migrate my personal projects to use your library. Again, awesome work and thank you so much!

**Comment by dj-nitehawk** [comment]
looks like we can already connect to a cluster with the advanced overload like so:
```csharp
            var settings = new MongoClientSettings
            {
                Servers = new[] {
                    new MongoServerAddress("localhost", 27027),
                    new MongoServerAddress("localhost", 27028),
                    new MongoServerAddress("localhost", 27029)
                },
                ConnectionMode = ConnectionMode.Automatic
            };

            new DB(settings, "database-name");
```
do you have a cluster to test it on?

**Comment by paolobriones** [comment]
@dj-nitehawk **tests look good on my cluster**, I disconnected the first server in the list and the API automatically switched to the second server in the cluster.

**Comment by dj-nitehawk** [comment]
awesome...
thanks.!
