### ISSUE TITLE
Unwind a multi nested object

### ISSUE THREAD

**Issue by LucaZiegler** [dj-nitehawk/MongoDB.Entities#61]
Hi,

how can I unwind a multi-nested object?
In my case Team => Dashboards => Versions => Widgets

So I have tried this is and it's working, but gives me the complete **Team** object:

```
var filter = Builders<Team>.Filter;
Team x0 = MongoDB.Entities.DB.Fluent<Team>()
                     .Match(filter.Eq("Dashboards.Versions.Widgets._id", ObjectId.Parse("...")))
                     .FirstOrDefault();
```

But I want to have only the **Widget** object. 
Something like this (not working):
```
Widget x0 = MongoDB.Entities.DB.Fluent<Team>()
                     .Match(x => Dashboards.Versions.Widgets.ID == ObjectId.Parse("...")))
                     .Unwind(x => x.Dashboards)
                     .Unwind(x => x.Versions)
                     .Unwind(x => x.Widgets)
                     .FirstOrDefault();
```

Is it then possible to update a property of Widget?
Like this:

```
x0.Description = "Test!";
x0.Save();
```

**Comment by dj-nitehawk** [comment]
i personally wouldn't touch deeply nested items like this with a 10ft. pole, but if you must, [here's](https://gist.github.com/dj-nitehawk/bd65e6e663847a19a3b07b46e540dd4d) how you'd do it.

there's no strongly typed way to achieve it with the official driver.

mongodb.entities has the [prop class](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/Extras#the-prop-class) to help with that.

**Comment by LucaZiegler** [comment]
@dj-nitehawk you are the best!
Thank you for example, that's working!
