### ISSUE TITLE
Query All Books with primary Author

### ISSUE THREAD

**Issue by ovaiss** [dj-nitehawk/MongoDB.Entities#62]
I need help with a query to get list of all books and primary author

Author Relationship
===============

public One<Author> PrimaryAuthor { get; set; }

Books Query
=========

var books = DB.Queryable<Book>().ToList();

Result
======
`[
  {
   "primaryAuthor": {
        "_id" : "AUTHOR ID"
   },
    "name": "Book Name"
  }
]`

But I need to get the results like:

`[
  {
   "primaryAuthor": {
        "_id" : "AUTHOR ID",
       "authorName": "Author Name",
   },
    "name": "Book Name"
  }
]`

**Comment by dj-nitehawk** [comment]
you requirement calls for an aggregation pipeline with a look up stage, which can be done like so:
```csharp
using MongoDB.Driver;
using MongoDB.Entities;
using MongoDB.Entities.Core;
using System.Linq;

namespace TestApp
{
    public class Book : Entity
    {
        public string Name { get; set; }
        public One<Author> PrimaryAuthor { get; set; }
    }

    public class Author : Entity
    {
        public string Name { get; set; }
    }

    public class BookWithAuthors : Book
    {
        public Author[] Authors { get; set; }
    }

    internal static class Program
    {
        private static void Main()
        {
            new DB("test");

            var authors = new[] {
                new Author { Name = "author one"},
                new Author { Name = "author two"}
            };

            authors.Save();

            var books = new[] {
                new Book { Name = "book one", PrimaryAuthor = authors[0]},
                new Book { Name = "book two", PrimaryAuthor = authors[0]},
                new Book { Name = "book three", PrimaryAuthor = authors[1]},
                new Book { Name = "book four", PrimaryAuthor = authors[1]},
            };

            books.Save();

            var result = DB.Fluent<Book>()
                           .Match(_ => true)
                           .Lookup<Book, Author, BookWithAuthors>(
                                DB.Collection<Author>(),
                                b => b.PrimaryAuthor.ID,
                                a => a.ID,
                                bwa => bwa.Authors)
                           .ToList();
        }
    }
}
```

**Comment by ovaiss** [comment]
> you requirement calls for an aggregation pipeline with a look up stage, which can be done like so:
> 
> ```cs
> using MongoDB.Driver;
> using MongoDB.Entities;
> using MongoDB.Entities.Core;
> using System.Linq;
> 
> namespace TestApp
> {
>     public class Book : Entity
>     {
>         public string Name { get; set; }
>         public One<Author> PrimaryAuthor { get; set; }
>     }
> 
>     public class Author : Entity
>     {
>         public string Name { get; set; }
>     }
> 
>     public class BookWithAuthors : Book
>     {
>         public Author[] Authors { get; set; }
>     }
> 
>     internal static class Program
>     {
>         private static void Main()
>         {
>             new DB("test");
> 
>             var authors = new[] {
>                 new Author { Name = "author one"},
>                 new Author { Name = "author two"}
>             };
> 
>             authors.Save();
> 
>             var books = new[] {
>                 new Book { Name = "book one", PrimaryAuthor = authors[0]},
>                 new Book { Name = "book two", PrimaryAuthor = authors[0]},
>                 new Book { Name = "book three", PrimaryAuthor = authors[1]},
>                 new Book { Name = "book four", PrimaryAuthor = authors[1]},
>             };
> 
>             books.Save();
> 
>             var result = DB.Fluent<Book>()
>                            .Match(_ => true)
>                            .Lookup<Book, Author, BookWithAuthors>(
>                                 DB.Collection<Author>(),
>                                 b => b.PrimaryAuthor.ID,
>                                 a => a.ID,
>                                 bwa => bwa.Authors)
>                            .ToList();
>         }
>     }
> }
> ```

Thanks for the answer, but this will result in array of authors, I just need one primaryauthor object

**Comment by dj-nitehawk** [comment]
```csharp
    public class BookWithAuthor : Book
    {
        public Author Author { get; set; }
    }

    var result = DB.Fluent<Book>()
                    .Match(_ => true)
                    .Lookup(DB.CollectionName<Author>(), "PrimaryAuthor.ID", "_id", "Authors")
                    .AppendStage<object>("{ $set : { Author : { $arrayElemAt : [ '$Authors', 0 ] } } }")
                    .As<BookWithAuthor>()
                    .ToList();
```
lookups with the c# driver is darn ugly i know. but there's no way around it.
