### ISSUE TITLE
JSON to Document Field

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#63]
I have an issue about saving new document to Mongo Collection with one 'object' field of mongo. When I try to action that, everything goes well except the object field like in the screenshot below:
![tumblr_odpfxknczs1v8ljkgo1_1280](https://user-images.githubusercontent.com/39852038/87854267-730fc480-c919-11ea-8e72-8d52e14a2eec.png)

### Request body: 
![Screenshot_20200718_170719](https://user-images.githubusercontent.com/39852038/87854294-9fc3dc00-c919-11ea-857c-3bbbd785f99f.png)

### Dto Class:
![Screenshot_20200718_171117](https://user-images.githubusercontent.com/39852038/87854307-bc601400-c919-11ea-9c6d-2874682e51f1.png)
The reason why I give object type to node, node will include dynamic fields which I cant strictly type it here.

#### Controller Side:
![Screenshot_20200718_171451](https://user-images.githubusercontent.com/39852038/87854378-43ad8780-c91a-11ea-9643-894df372621d.png)

### The action starts here:
![Screenshot_20200718_170748](https://user-images.githubusercontent.com/39852038/87854292-98043780-c919-11ea-99a8-cd0435ac6772.png)

However, if I give C# object to node field, like `
new {
   test = "anythin"
}
` then it works like expected. But it doesnt work with the dto which mapped with json body of the http request. I couldnt see how to save the json objects in to the db. A working code example would perfectly help.

**Comment by dj-nitehawk** [comment]
you will have to json-stringify the value before posting so the posted json will be like this:
```java
{
    "node" : "{\"test\":1,\"child\":[1]}"
}
```
classes will look like this:
```csharp
    public class CreateContentDTO
    {        
        public string node { get; set; }
    }

    public class ContentEntity : Entity
    {        
        public BsonDocument node { get; set; }
    }
```
in the repository, do this:
```csharp
    var entity = new ContentEntity
    {
        node = BsonDocument.Parse(dto.node)
    };
    
    entity.Save();
```
