### ISSUE TITLE
Change streams

### ISSUE THREAD

**Issue by davidguidali** [dj-nitehawk/MongoDB.Entities#64]
Hi 
Very nice library, I love it!
Is there already any support for change streams?
Something like db.changed += ondbchanged(..) would be insane! 
br

**Comment by dj-nitehawk** [comment]
thanks for the feedback.
i haven't had the chance to play with change streams yet. 
will look in to it soon and implement if feasible.

**Comment by dj-nitehawk** [comment]
good news...
work has begun on change streams. https://github.com/dj-nitehawk/MongoDB.Entities/blob/dev/MongoDB.Entities/Utilities/Watcher.cs
looks promising. if everything works out ok, will be able to release in a couple of days.

**Comment by dj-nitehawk** [comment]
it's done: 

https://github.com/dj-nitehawk/MongoDB.Entities/wiki/14.-Change-Streams

thanks for the suggestion!

**Comment by ehigiepaul** [comment]
Nice addition and on time. 👏👏👏

**Comment by ehigiepaul** [comment]
Change Stream works like a charm. Thank for the update.

**Comment by dj-nitehawk** [comment]
i just put change-stream watchers on steroids ;-)
the api had to change a little bit though.
wiki page has been updated.

**Comment by davidguidali** [comment]
iWow cool, thanks very much!

**Comment by davidguidali** [comment]
Done :)
