### ISSUE TITLE
Updating single entity or leaving it as it is

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#65]
As in the documentation [here](https://github.com/dj-nitehawk/MongoDB.Entities/wiki/02.-Entities#updating-entities-without-retrieving) I am updating the entities in the document of my mongo collection.

Like this:
`
DB.Update<ContentEntity>().Match(item => item.ID == id)
    .Modify(item => item.name, dto.name)
    .Execute();
`
But how can I leave the entity as it is if 'dto.name' comes null from request ?

My current solution:

<img width="574" alt="Screen Shot 2020-07-20 at 13 58 42" src="https://user-images.githubusercontent.com/39852038/87930684-2ea73480-ca91-11ea-8425-8b016a4f3bdc.png">

Is there any way to do this quicker without 2 times accessing to database ?

**Comment by dj-nitehawk** [comment]
how about something like this:
```csharp
    var propCount = 0;
    var update = DB.Update<ContentEntity>().MatchID(id);

    if (!string.IsNullOrEmpty(dto.name))
    {
        update.Modify(item => item.name, dto.name);
        propCount++;
    }

    if (dto.age > 0)
    {
        update.Modify(item => item.age, dto.age);
        propCount++;
    }

    if (propCount > 0)
    {
        update.Execute();
    }
```

**Comment by ozkanonur** [comment]
> how about something like this:
> 
> ```cs
>     var propCount = 0;
>     var update = DB.Update<ContentEntity>().MatchID(id);
> 
>     if (!string.IsNullOrEmpty(dto.name))
>     {
>         update.Modify(item => item.name, dto.name);
>         propCount++;
>     }
> 
>     if (dto.age > 0)
>     {
>         update.Modify(item => item.age, dto.age);
>         propCount++;
>     }
> 
>     if (propCount > 0)
>     {
>         update.Execute();
>     }
> ```

yes thats better way, thank you
