### ISSUE TITLE
Question: use in .netcore web api

### ISSUE THREAD

**Issue by brooksyott** [dj-nitehawk/MongoDB.Entities#68]
Good day,

I've looked at your service stack webapi example, but I'm wonder if you have a netcore webapi example. Specifically, how to initialize the database (ie. singleton, scoped), for user with a service.

I'm fairly new to netcore webapi, so my appologies for the simple question. I've googled and couldn't find an example.

Dave

**Comment by dj-nitehawk** [comment]
it's shown in the wiki here: 
https://github.com/dj-nitehawk/MongoDB.Entities/wiki/01.-Getting-Started#aspnet-core-basic-initialization

let me know if you need further help.

**Comment by kyro-dev** [comment]
> it's shown in the wiki here:
> https://github.com/dj-nitehawk/MongoDB.Entities/wiki/01.-Getting-Started#aspnet-core-basic-initialization
> 
> let me know if you need further help.

I cannot access the wiki. How would I go about this?

**Comment by dj-nitehawk** [comment]
please see this example .net core web api project
https://github.com/dj-nitehawk/MongoDB-Entities-Repository-Pattern

**Comment by kyro-dev** [comment]
Thanks
