### ISSUE TITLE
using with Azure functions 

### ISSUE THREAD

**Issue by parmarnishant** [dj-nitehawk/MongoDB.Entities#7]
Hi,
I am trying to use this with Azure functions and use single instance of DB by doing : 

private static Lazy<DB> lazyClient = new Lazy<DB>(InitializeDBfunction);
private static DB client => lazyClient.Value;

The problem is that above function is never called if i do Entity.Save().
Please recommend usage of this library with Azure functions.

Thanks

**Comment by dj-nitehawk** [comment]
i'm assuming something like this could work:
```csharp
            var settings = MongoClientSettings.FromUrl(new MongoUrl("AF mongodb connection string"));
            settings.SslSettings = new SslSettings() { EnabledSslProtocols = SslProtocols.Tls12 };

            //no need to store DB in a variable as it is already a static class
            new DB(settings, "database name");

            var result = DB.Queryable<MyEntity>()
                           .Where(x => x.ID == "some id")
                           .Single();
```
give it a shot and let me know if it works...

**Comment by dj-nitehawk** [comment]
assuming the above code solves it. if you need further help, pls reopen ticket.
