### ISSUE TITLE
Change the "ID" field to "Id"

### ISSUE THREAD

**Issue by bryanmatteson** [dj-nitehawk/MongoDB.Entities#70]
This way, when libraries that automatically camelcase the name of the fields (json serialization, graphql model serialization), it will get named "id" rather than "iD". This is the conventional way of casing Id fields.

Since we are required to inherit from Entity or implement IEntity, this should really follow Microsoft conventions on casing.

This is what I have to do in all of my models just to get behavior that would work automatically if the field were named "Id".

```
[Name("results")]
public class OrderResults: Results, IEntity, IModifiedOn {
    [GraphQLName("id"), GraphQLType(typeof(NonNullType<IdType>))]
    [BsonId, BsonRepresentation(BsonType.ObjectId)]
    public string ID { get; set; } = ObjectId.GenerateNewId().ToString();

    public DateTime ModifiedOn { get; set; } = DateTime.Now;
}
```

**Comment by dj-nitehawk** [comment]
just implement `IEntity` once in a base class and inherit everywhere like this:
```csharp
public class BaseEntity : IEntity, IModifiedOn
{
    [
        GraphQLName("id"),
        GraphQLType(typeof(NonNullType<IdType>)),
        ObjectId,
        BsonId
    ]
    public string ID { get; set; } = ObjectId.GenerateNewId().ToString();

    public DateTime ModifiedOn { get; set; } = DateTime.Now;
}

public class Results : BaseEntity
{
    public string SomeProp { get; set; }
}

[Name("results")]
public class OrderResults : Results
{
    public string AnotherProp { get; set; }
}
```

**Comment by bryanmatteson** [comment]
That's assuming I don't already need to inherit from another class already, and that I can refactor the code to make that necessary. This isn't always the case. For example, in my code samply, you'll notice I already inherit from Results. That class comes from a library, which is the reason I take on the IEntity rather than inherit from Entity.

**Comment by bryanmatteson** [comment]
ObjectId, GenerateNewId, IdType, BsonId. All of these follow the "Id" convention. Your "ID" is the only one that doesn't follow the conventions and creates extra work or forces a developer into a certain class hierarchy. It's a shame you won't fix.

**Comment by dj-nitehawk** [comment]
i understand your frustration mate. 
to be honest, i've never seen data entities being used like this.
typically you'd isolate data entities in their own layer and map them to domain entities with automapper or something.
so, i'd have to dismiss your request as "unsupported usage" as it would anger a lot of people if i renamed the `ID` property.
personally, i need it to be `ID` in my projects to differentiate between another `Id` property i have on some of my entities.

**Comment by dj-nitehawk** [comment]
another alternative is for you to fork the source and make your own version of the library with an `Id` property on `IEntity`

**Comment by bryanmatteson** [comment]
Thank you for the quick response.
