### ISSUE TITLE
Resolving DbRef

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#72]
### How can I resolve the referenced collection on Find operations ?

![160042173065645098](https://user-images.githubusercontent.com/39852038/93583031-f4341800-f9ab-11ea-80b6-64e21dfa83c0.jpg)

### When I read the document, the referenced document values are comes as following
![a](https://user-images.githubusercontent.com/39852038/93582992-eb434680-f9ab-11ea-86a5-78ea8d82a895.png)

**Comment by dj-nitehawk** [comment]
this library doesn't use DBRefs. it seems like you used something else to create the data.
please see [this answer](https://github.com/dj-nitehawk/MongoDB.Entities/issues/69#issuecomment-683893907) to see how mongodb.entities can resolve referenced entities.

let me know if you need any further help. i can look in to it deeper if you post the json data from mongodb (instead of images) so i can simply insert it into my mongodb to play around with. posting your entity definitions (c# classes) would also help.

**Comment by ozkanonur** [comment]
Alright, let me write the scenario down.

### Menu Entity
```cs
public class MenuEntity : Entity
{
    public string title { get; set; }
    public string url { get; set; }
    public Status status { get; set; }
    public BsonArray items { get; set; }
    public DateTime createdOn { get; set; }

    public MenuEntity()
    {
        createdOn = DateTime.UtcNow;
    }
}
```

### Layout Entity
```cs
public class LayoutEntity : Entity
{
    public string title { get; set; }
    public string description { get; set; }
    public Status status { get; set; }
    public BsonArray designSchema { get; set; }
    public string createdBy { get; set; }
    public string modifiedBy { get; set; }
    public DateTime createdOn { get; set; }

    public LayoutEntity()
    {
        createdOn = DateTime.UtcNow;
    }
}
```

### In LayoutEntity, the designSchema field gets something like following

```json
[
	{
		"type": "column",
		"props": {
			"size": "6",
			"tabletSize": "12",
			"hideOnTablet": false,
			"mobileSize": "12",
			"hideOnMobile": false
		},
		"definitions": {
			"id": "d150a993-7033-490e-bf7d-f46320886187",
			"name": "column1"
		},
		"children": [
			{
				"type": "image",
				"data_type": "static",
				"props": {
					"path": "logo.jpg",
					"quality": "medium"
				},
				"definitions": {
					"id": "2744566ca-6ce1-4478-be20-938333fea213",
					"name": "image1"
				},
				"children": [],
				"options": {}
			},
			{
				"type": "heading",
				"data_type": "meta",
				"props": {
					"text": "post.title",
					"type": "h1"
				},
				"definitions": {
					"id": "2744566ca-6ce1-4478-be20-938333fea213",
					"name": "image2"
				},
				"children": [],
				"options": {}
			},
			{
				"type": "label",
				"data_type": "meta",
				"props": {
					"text": "meta.isbn.text"
				},
				"definitions": {
					"id": "2744566ca-6ce1-4478-be20-938333fea213",
					"name": "image2"
				},
				"children": [],
				"options": {}
			},
			{
				"type": "menu",
				"props": {
					"id": "5f6504475d441102897348bf",
					"level": 1,
					"items": []
				},
				"definitions": {
					"id": "336cce1b-f7a7-44d9-9b71-89d633d469af",
					"name": "button2"
				},
				"children": [],
				"options": {}
			}
		],
		"options": {}
	},
	{
		"type": "column",
		"props": {
			"size": "6",
			"tabletSize": "12",
			"hideOnTablet": false,
			"mobileSize": "12",
			"hideOnMobile": false
		},
		"children": [],
		"definitions": {
			"id": "4efa9a78-1457-4b60-8bc6-342d1c4fc9db",
			"name": "column2"
		},
		"options": {}
	}
]
```

So in the array object above, I get the id of each object whose type equals to menu(could be anywhere in objects, like 45th sub children of main children). Then I query the DB with these IDs and place the returned menu object in the children of the object whose type is the menu.

There is no problem so far, but when I update any of MenuEntity, I need to update that also in every designSchema of LayoutEntity.

Its very complicated and hard to manage menu objects on update operations, so I wanted to look at the reference system of MongoDB. But I couldn't resolve the value of DbRef.

**Comment by dj-nitehawk** [comment]
> what I want to do is that when MenuEntity is updated their references should automatically be updated

there is no such feature in mongodb server. even [DBRef](https://docs.mongodb.com/manual/reference/database-references/index.html#dbrefs) is simply a convention. it doesn't automatically resolve references. from mongodb documentation:
> To resolve DBRefs, your application must perform additional queries to return the referenced documents.

if you duplicate data, you must update each copy manually. looks like you might have to rethink your schema design. can't really help much as i really don't understand your problem domain.

in any case, to update deeply nested objects like this, you need to use array filter updates. here are some examples:
- https://mongodb-entities.com/wiki/Entities-Update.html#array-filter-updates
- https://mongodb-entities.com/wiki/String-Templates.html#update-with-array-filters
- https://gist.github.com/dj-nitehawk/bd65e6e663847a19a3b07b46e540dd4d#file-program-cs-L62

maybe this one is for stackoverflow. if someone can give you a good answer using even the official driver, i can help convert it to mongodb.entities

good luck!

**Comment by ozkanonur** [comment]
I thought maybe there would be way to get updates automatically when original document gets updated. Anyway, I will need to deal with this manually. Thank you for quick response!
