### ISSUE TITLE
The type initializer for 'MongoDB.Entities.Cache`1' threw an exception.

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#74]
I have gotten this exception several times but I'm unable to consistently reproduce it. My use case is that I have a List<Entity> that I typically call SaveAsync() on, these lists typically have several million objects in it (due to processing). 

This only started happening after upgrading to v20.

**The type initializer for 'MongoDB.Entities.Cache`1' threw an exception.**
System.TypeInitializationException: The type initializer for 'MongoDB.Entities.Cache`1' threw an exception.

---> System.NullReferenceException: Object reference not set to an instance of an object. 
at int System.Collections.Generic.Dictionary<TKey, TValue>.FindEntry(TKey key) 
at bool System.Collections.Generic.Dictionary<TKey, TValue>.TryGetValue(TKey key, out TValue value) 
at IMongoDatabase MongoDB.Entities.TypeMap.GetDatabase(Type entityType) 
at static MongoDB.Entities.Cache<T>() 
--- End of inner exception stack trace --- 
at IMongoCollection<T> MongoDB.Entities.Cache<T>.get_Collection() 
at IMongoCollection<T> MongoDB.Entities.DB.Collection<T>() 
at IMongoQueryable<T> MongoDB.Entities.DB.Queryable<T>(AggregateOptions options, IClientSessionHandle session)

**Comment by paolobriones** [comment]
Digging into this a little further, based on what i have on the logs, this occurs when querying the database using LINQ:

DB.Queryable<Entity>().FirstOrDefaultAsync(i => i.param1 == value1 && i.param2 == value2);

**Comment by dj-nitehawk** [comment]
this one took a bit of head scratching but i believe i've got a fix.
even though i wasn't able to reproduce it locally, i'm assuming this is a high concurrency issue.
can you please upgrade to the latest beta `Install-Package MongoDB.Entities -Version 20.1.0-beta1` and see if the problem disappears?

thanks for reporting this!!!

**Comment by paolobriones** [comment]
Ok, will install the beta version and try it out; ill get the code to go thru that million object SaveAsync() and DeleteAsync().

Will let you know the results soon, thanks again!

**Comment by paolobriones** [comment]
**Tried it out with 20.1.0-rc, 15million records.. no exceptions**

Both SaveAsync() and DeleteAsync() completed several times without exceptions

Excellent work!
