### ISSUE TITLE
Does MongoDB recreate an existing index on the collection during startup?

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#76]
I added the DB.Index()...CreateAsync() on the static ctor of my entity classes as you recommended in the documentation.

Does MongoDB detect these existing Indexes with the same keys and ignores any subsequent calls to create the same index?

**Comment by dj-nitehawk** [comment]
yes that is the behavior of mongodb server, if the keys are the same, the command is ignored.
if the goal is to recreate/rebuild indexes, you need to drop and create the indexes again.
