### ISSUE TITLE
How to use MongoDB.Bson.ObjectId as Id

### ISSUE THREAD

**Issue by LucaZiegler** [dj-nitehawk/MongoDB.Entities#79]
How can I use `MongoDB.Bson.ObjectId` as an Entity Id instead of a string?

I tried this:

`
public class Query : IEntity
   {
      [BsonId, ObjectId]
      public ObjectId Id
      {
         get; set;
      }
   }
`

but this returns null:
`var query = MongoDB.Entities.DB.Queryable<Query>().FirstOrDefault(x => x.Id == queryID);`

This is possible in the offical MongoDB.Driver, please implement it...

**Comment by dj-nitehawk** [comment]
if you have a look in the database, you'll see that `_id` field is stored as `ObjectId`. in the c# world we deal with a string representation of objectid to make our lives easier. it was a design choice made in the early days of the library. it is not possible to change the type of the `IEntity.ID` property.

however, you are free to add another property to your entity classes with `ObjectId` if your application depends on it. but it can't be `[BsonId]`.

**Comment by dj-nitehawk** [comment]
here's an example:
```csharp
using MongoDB.Bson;
using MongoDB.Driver;
using MongoDB.Driver.Linq;
using MongoDB.Entities;
using System.Linq;
using System.Threading.Tasks;

namespace TestProg
{
    internal static class Program
    {
        public class Author : Entity
        {
            public ObjectId BookID { get; set; }
        }

        private static async Task Main()
        {
            await DB.InitAsync("test", "localhost");

            var id = ObjectId.GenerateNewId();

            await new Author { BookID = id }.SaveAsync();

            var res = await DB.Queryable<Author>()
                              .Where(a => a.BookID == id)
                              .FirstOrDefaultAsync();
        }
    }
}
```

**Comment by LucaZiegler** [comment]
Hm ok I come from the official MongoDB driver and this means that I have to switch all ObjectId's to string 😢

**Comment by dj-nitehawk** [comment]
migrating an existing project will be a pain either way :-)
some compromises had to be made with the flexibility to support the features of this library.

**Comment by LucaZiegler** [comment]
Ok, thank you for your fast support and the great work!

**Comment by dj-nitehawk** [comment]
you're most welcome!
if you need any other info/help with the library or even some querying help, don't hesitate to ask.
have a great day!
