### ISSUE TITLE
Combine Fuzzy + Many searches

### ISSUE THREAD

**Issue by LukePammant** [dj-nitehawk/MongoDB.Entities#81]
Hey I'm looking to do a fuzzy search but also limit all results by some other properties on the object. For example I'd like to make sure that a documents 'OrganizationId' is set to a specific value and do a fuzzy search on the 'Names' field in all the documents with that 'OrganizationId'.

**Comment by dj-nitehawk** [comment]
the text index search has to be the first stage in the pipeline. so first you search the index for the search term and then filter on the other criteria in subsequent pipeline stages like so:
```csharp
using MongoDB.Driver;
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestProg
{
    internal static class Program
    {
        public class Comapany : Entity
        {
            public FuzzyString Name { get; set; }
            public int OrganizationId { get; set; }
        }

        private static async Task Main()
        {
            await DB.InitAsync("test", "localhost");

            await DB.Index<Comapany>()
                    .Key(c => c.Name, KeyType.Text)
                    .CreateAsync();

            await new[] {
                new Comapany{ Name = "marks & spencer", OrganizationId = 1 },
                new Comapany{ Name = "markus spincer", OrganizationId = 2 },
                new Comapany{ Name = "facebook & co", OrganizationId = 3 },
            }.SaveAsync();

            var result = await DB.FluentTextSearch<Comapany>(Search.Fuzzy, "marks")
                                 .Match(c => c.OrganizationId == 1)
                                 .ToListAsync();
        }
    }
}
```

**Comment by LukePammant** [comment]
Awesome, thanks! If the OrganizationID is more limiting than the fuzzy search but the fuzzy search executes first it might be scanning through more documents than it needs to. Will that slow down the results on the MongoDB side? Or is that optimization handled already by MongoDB?

**Comment by dj-nitehawk** [comment]
mongo server [only uses the index for the first match stage](https://docs.mongodb.com/manual/core/aggregation-pipeline/#pipeline-operators-and-indexes). the text search query above translates into the following pipeline:
```java
[
    {
        "$match": {
            "$text": {
                "$search": "MRKS"
            }
        }
    },
    {
        "$match": {
            "OrganizationId": 1
        }
    }
]
```
so only the first $match stage will use an index. the next $match stage will have to inspect the matched documents from the first stage to see if the organization id is a match. i'm not too sure if this is done in memory or not. maybe it's a question for stackoverflow...
