### ISSUE TITLE
[contributions needed] create a cheat-sheet for mongodb.entities

### ISSUE THREAD

**Issue by paolobriones** [dj-nitehawk/MongoDB.Entities#83]
The feature-set is growing and there's a lot of ways to do things via the MongoDB Driver and thru MongoDB.Entities. 

It would be a great help to people getting started with MongoDB.Entities if they had a quick reference cheat sheet of different ways to query the data or different ways to do things specific to MongoDB.Entities. The current documentation is awesome, but sometimes, I would like to just see what's available and if I needed more information then I drill down to that specific functionality.

**Comment by dj-nitehawk** [comment]
that is a great idea...
however, with my current workload, it would take some time to materialize.
maybe this could take community contributions. 
at least just a list of cheats/walkthroughs people would like included in the cheat-sheet.
better yet, create some [gists](https://gist.github.com/) and post the link in this thread.
i will then categorize, improve, cleanup and add it to the cheat-sheet documentation with accreditation.

there's already some [gists](https://gist.github.com/dj-nitehawk/public) i created here if anyone's interested.

**Comment by dj-nitehawk** [comment]
if anybody's interested in writing detailed guides/tutorials/walkthroughs etc, please post them on https://dev.to (or if you have your own blog, you can post there) and let me know the links and i will add them to the documentation with accreditation.

**Comment by paolobriones** [comment]
I'll definitely contribute some by next week, hopefully, my schedule clears up

**Comment by dj-nitehawk** [comment]
added a cheat-sheet section to the documentation site: https://mongodb-entities.com/cheat-sheet/
let me know if the instructions aren't clear there...

**Comment by dj-nitehawk** [comment]
cheet sheet has been abolished for now. kinda seemed redundant having the same info in two places. also found it tedious to maintain. maybe in the future, we'll come up with an `advanced tips & tricks` document to showcase everything that's not already mentioned in the main docs.
