### ISSUE TITLE
Raw Queries

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#86]
I couldn't see it documentation so I am asking here, does this lib support raw queries  like <code>db.inventory.find({ "data.name" : "example" })</code> ?

**Comment by dj-nitehawk** [comment]
it's documented here: https://mongodb-entities.com/wiki/String-Templates.html

**Comment by dj-nitehawk** [comment]
you can also do this if you like:
```csharp
FilterDefinition<Inventory> filter = "{ 'data.name' : 'example' }";

var res = (await DB.Collection<Inventory>()
                   .FindAsync(filter)
          ).ToList();
```
you might as well use the official driver in this case :-)

**Comment by ozkanonur** [comment]
@dj-nitehawk  second one works crystal clear, thanks!
