### ISSUE TITLE
Is there class mapping ?

### ISSUE THREAD

**Issue by WhiteBookmark** [dj-nitehawk/MongoDB.Entities#9]
Hi

I just wanted to ask if I can still use attributes for class mapping. For [example](http://mongodb.github.io/mongo-csharp-driver/2.5/reference/bson/mapping/),

If I want to defined the BSONRepresentation type to string/int or any, I would use:

`[BsonRepresentation(BsonType.Double)]`
`public double MinimumDoubleValue { get; set; } = 0.00150000;`

Does this library support representation attributes and others ? or do I not need to write them and the library will automatically use the datatype as described for the properties.

P.s. I just don't want int, double numbers to be inserted as strings in the DB.

**Comment by dj-nitehawk** [comment]
you don't need them. types are automatically mapped to the correct mongo data types. here's an example:
```csharp
    public class User : Entity
    {
        public string String { get; set; }
        public DateTime Date { get; set; }
        public int Integer { get; set; }
        public decimal Decimal { get; set; }
        public double Double { get; set; }
        public float Float { get; set; }
        public long Long { get; set; }
    }
```
gets stored in mongodb like so:
```java
{
    "_id": ObjectId("5d4b884fcd4af30a3cbd1d9b"),
    "String": "this is a string",
    "Date": ISODate("2019-08-08T02:26:23.567Z"),
    "Integer": NumberInt("123"),
    "Decimal": NumberDecimal("123.45"),
    "Double": 123.45,
    "Float": 123.449996948242,
    "Long": NumberLong("1234567890")
}
```
you can however use them if you prefer. because this library is just an abstraction layer on top of (a cleaner api for) the official driver.

let me know if you need help with anything else.

**Comment by WhiteBookmark** [comment]
Thanks for help
