### ISSUE TITLE
Could not able to find email

### ISSUE THREAD

**Issue by schauhan232** [dj-nitehawk/MongoDB.Entities#91]
First of all Sorry for generating issue because I am not sure this is issue or not, but looks like this is something missing from the C# driver it self.

I have a scenario where I created text index on, email, firstname, lastname.

When I do exact search from mongo shell like 
![image](https://user-images.githubusercontent.com/36223021/101155008-8fa06500-364c-11eb-876d-35b1516131ba.png) I am able to get exactly 1 matching record

While If I search , I got all the matching records with containing com, gmail because there is not phrases search.

![image](https://user-images.githubusercontent.com/36223021/101156940-5f0dfa80-364f-11eb-83bf-7f59bc85786b.png)

I am trying to find the exact syntax in which I can pass exact phrase, can you please point out how to use exact phrase search in this ?

**Comment by dj-nitehawk** [comment]
you just need to escape the quotation marks when doing the search:
```csharp
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestApplication
{
    public class Subscription : Entity
    {
        public string Name { get; set; }
        public string Email { get; set; }
    }

    public static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("test");

            await DB.Index<Subscription>()
                    .Key(s => s.Name, KeyType.Text)
                    .Key(s => s.Email, KeyType.Text)
                    .CreateAsync();

            await new[] {
                new Subscription { Name = "one", Email = "one@gmail.com" },
                new Subscription { Name = "two", Email = "two@gmail.com" }
            }.SaveAsync();

            var subs = await DB
                .Find<Subscription>()
                .Match(Search.Full, "\"two@gmail.com\"")
                .ExecuteAsync();
        }
    }
}
```

**Comment by schauhan232** [comment]
Thanks for the prompt reply, Appreciate your help.
