### ISSUE TITLE
Transactional update from DB static class

### ISSUE THREAD

**Issue by ItSkary** [dj-nitehawk/MongoDB.Entities#92]
I am not finding a way to use IClientSessionHandle in during an update (using DB static class).
So basically seems to me that i can use method "SaveAsync", and "DeleteAsync" in the same transaction, but not an "UpdateAsync" method.

So i would ask, after starting a transaction how can i use update from DB static class? 
eg : 

```csharp
var tran  = DB.Transaction() //somewhere i begin transaction and  pass through my repository

public void RepositoryDoJob ( Entity entity1 , ..., Entity entity4 , ... , IClientSessionHandle session){
  DB.SaveAsync(entity1 , session);
  DB.SaveAsync(entity2 , session);
  DB.DeleteAsync(entity3 , session);
  DB.Update()
    .MatchID(entity4.ID)
    .ExectueAsync() // ??how to join the transaction ??
      
  //The only solution i came to is to pass a Transaction object to repository, 
  //but then i had to choose if invoke method on Transaction or DB
}
```

Reading the source i get the sensation that a overload is missing here, in fact the Update command constructor support transaction : 

```
         /// <summary>
        /// Starts an update command for the given entity type in the transaction scope.
        /// </summary>
        /// <typeparam name="T">The type of entity</typeparam>
        public Update<T> Update<T>()
        where T : IEntity
        {
            return new Update<T>(this.Session);
        }
```
Thanks in advance for clarification and for the great job done so far.

EDIT : Workaround
______________________________________________________________________________________
By now i am testing this workaround, but it seems to me a very ugly solution, so a more consistent approach is welcome
```csharp
var relevantConstructor = typeof(Update<Entity>).GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance).FirstOrDefault();
            Update<Entity> updateAction = (Update<Entity>)relevantConstructor?.Invoke ( new object[]{ session} );

            var result = updateAction.Match ( deleteCriteria )
                            .Modify ( item => (item as IVirtualEreasable).IsActive , false )
                            .ExecuteAsync();`
```

PS : it's not clear to me why code appear so ugly, probably i use some character in the code that mess with the editor.
My apologies for that.

**Comment by dj-nitehawk** [comment]
is this what you're sorta trying to do?
```csharp
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestApplication
{
    public class Book : Entity
    {
        public string Title { get; set; }
    }

    public static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("Test");

            var book = new Book { Title = "book 1" };
            await book.SaveAsync();

            var book2 = new Book { Title = "book 2" };

            var TN = DB.Transaction<Book>();

            await TN.SaveAsync(book2);

            await RepositoryDoJob(TN, book, book2);
        }

        private static async Task RepositoryDoJob(Transaction TN, Book entity1, Book entity2)
        {
            entity1.Title = "updated book1";
            await TN.SaveAsync(entity1);

            await TN.Update<Book>()
                    .MatchID(entity2.ID)
                    .Modify(e => e.Title, "updated book2")
                    .ExecuteAsync();

            await TN.CommitAsync();
        }
    }
}
```

**Comment by ItSkary** [comment]
Exactly, my problem is that in my scenario transaction object (TN) is optional (basically i have two repository and sometimes i would made them operate transactionally).
So i need to write the logic that operate on transaction object when supplied, or to DB static class if transaction object is not provided.
I don't like that and try to find a common way to handle that (i also find bad build a transaction even when not needed).

By now i found a way to provide the session to the Update, but is really ugly and suppose there is a better one

**Comment by dj-nitehawk** [comment]
ok i understand your requirement now. i'll add overloads that take `IClientSessionHandle` to the following:
```csharp
DB.Update<T>
DB.UpdateAndGet<T>
DB.Find<T>
```
that would solve your problem right?

**Comment by ItSkary** [comment]
Yes absolutley.
Thanks again for the help.

**Comment by dj-nitehawk** [comment]
v20.5.1 is out on nuget :-)

**Comment by ItSkary** [comment]
Amazingly fast :)
Thanks again
