### ISSUE TITLE
The type initializer for 'MongoDB.Entities.Cache`1'

### ISSUE THREAD

**Issue by StevenSKing** [dj-nitehawk/MongoDB.Entities#93]
It's Work some Time throw this error, then  break my service 
I catch the Error Messege :
The type initializer for 'MongoDB.Entities.Cache`1' threw an exception.
Error TrackStack ：
System.InvalidOperationException: Database connection is not initialized for [Default]\r\n   at MongoDB.Entities.DB.Database(String name)\r\n   at MongoDB.Entities.TypeMap.GetDatabase(Type entityType)\r\n   at MongoDB.Entities.Cache`1..cctor()

how can I resolve this？

**Comment by dj-nitehawk** [comment]
i believe this is happening due to high concurrency. please update to v20.6 and the issue should disappear. if not, please let me know what type of application this is and where/how you initialize the databases.
