### ISSUE TITLE
Improvement : custom entity ID without re-implement from IEntity

### ISSUE THREAD

**Issue by ItSkary** [dj-nitehawk/MongoDB.Entities#94]
As stated in the title, my request is not about a bug, but a suggestion for an improvement.
If i would a custom ID for a specific entity, i have to inherit from IEntity (instead of Entity) and implement my custom version of the  method GenerateNewID and a property called ID (with the same attribute of the ID property in the Entity class).
I am thinking if is not a better idea make the method 'GenerateNewID' (in the abstract class Entity) virtual ,so that i have simply to overload it.

Thanks in advance for clarification.

**Comment by dj-nitehawk** [comment]
absolutely. no idea how that slipped under my radar. already pushed out v2.6.1 with it.
thanks for the suggestion...

**Comment by ItSkary** [comment]
Thanks, super-fast as usual 👍
