### ISSUE TITLE
Strange bheaviuor with derived class

### ISSUE THREAD

**Issue by ItSkary** [dj-nitehawk/MongoDB.Entities#95]
As stated in the title, i see a strange behaviour when try to save a derived type.
Not clear if it's a bug or a "feature" inherited from MongoDB driver, but it's at least misleading in some situation, and accordingly with what is written in documentation.

Here the example : 
```csharp
 Person model = Person.BuildModel_Simple();

            Random rng = new Random();
            model.Name += rng.Next(10000, 99999).ToString();

            var task = MongoDB.Entities.DB.SaveAsync<Entity>(model);
            task.Wait();

            var result = task.Result;

            Assert.IsTrue(result?.UpsertedId != null);
````

And here the definition of Person 
```csharp
[Name("Person")]
public class Person : Entity, ICreatedOn, IModifiedOn
{
    public string Name { get; set; }
    public string Surname { get; set; }
    public DateTime DateOfBirth { get; set; }
    public DateTime CreatedOn { get; set; }
    public DateTime ModifiedOn { get; set; }
        
    public override string GenerateNewID() 
        => $"{(this.Name ?? "").Trim()}{(this.Surname ?? "").Trim()}".ToSubSHA256();
}
```

Now accordingly to the configuration i have set the entity name ( named "Person") so when i save it, a collection named "Person" should created regardeless of the type.

But if my saving command is : 
`var task = MongoDB.Entities.DB.SaveAsync<Entity>(model);`

Then the collection is named Entity : 
![image](https://user-images.githubusercontent.com/6507710/104752907-8defb400-5757-11eb-9967-cf004a25792c.png)

If i change the save command to : 
`var task = MongoDB.Entities.DB.SaveAsync<Person>(model);`
everything working fine

Mistery in the mistery i see a new property (in the mongo document) named _t that refer the correct type/name.
A bit confused on what's going on.

My goal is to save derived type in different collection.

Ps : 
i have now noticed that when i save thorugh the "Entity" (the faulty one) version of the command the CreatedOn and ModificedOn property are not considered.
That part is handled in that library (MongoDB.Entities) so this let me suppose that somewhere in the library code, the generic type of SaveAsync method is checked instead of the type of the actual instance provided.

PPs : 
after a bit of digging in the library code here my suspected line of code
![image](https://user-images.githubusercontent.com/6507710/104755862-4e2acb80-575b-11eb-947d-f0ca17af82c6.png)
![image](https://user-images.githubusercontent.com/6507710/104755891-5551d980-575b-11eb-9259-fc480bdebab8.png)

in yellow the problem about date
in azure the problem about the attribute

It's not clear to me (but i have to admit that i have not completley clear the architecture) why cache work on the generic type and not over instance type

**Comment by dj-nitehawk** [comment]
`DB.SaveAsync<Entity>` is currently not supported. you need to specify the final derived type `DB.SaveAsync<Person>` in order for it to work properly. this is a known limitation atm. i will dig deeper in to a solution when i get some free time.

so, to summarize, you wanna be able to work with a base type `Entity` only and not specify the exact derived type in your code right?

it would help if you give me an example scenario to work with. why exactly do you need this functionality?
seems like you're doing some whacky business in your code :-)

**Comment by paolobriones** [comment]
I agree with @dj-nitehawk

my opinion is that the exact type should be used in the api explicitly (or via inference). By allowing DB.SaveAsync<Entity>() would introduce messy usage patterns and would require reflection that can be avoided by just specifying the correct type.

**Comment by ItSkary** [comment]
I have used Entity just for convenience in the example i have rewritten it : 

`
        [TestMethod]
        public void PlainDirectWrite()
        {
            JetPilot model = JetPilot.BuildModel_SimpleJetPilot();

            Random rng = new Random();
            model.Name += rng.Next(10000, 99999).ToString();

            var task = MongoDB.Entities.DB.SaveAsync<Person>(model);
            task.Wait();

            var result = task.Result;

            Assert.IsTrue(result?.UpsertedId != null);
        }
`
![image](https://user-images.githubusercontent.com/6507710/104762432-a1554c00-5764-11eb-9805-2b94b7700d9c.png)


Where JetPilot inherits form Person, then same problem I get a JetPilot in the wrong collection.
ATM i am not writing actually production code, i was just studing the library trying some kata like execrices.

Happened that i try to save a derived POCO class using the parent repository because it's a derived type so it's a super legit action to do.
I understand that is reasonable to put the derived item in the parent collection, but if there is an attribute that let me specify the target collection i expect to be able to enforce a different bheaviour.

**Comment by dj-nitehawk** [comment]
well it seems like you have a choice to make then...

1. either use the final derived type `DB.SaveAsync<JetPilot>(model)`
2. or simply do `model.SaveAsync()`

was just going over the library code, and it doesn't seem like an easy refactor to support this.
but i'll keep messing around with it...
no promises however ;-)

**Comment by ItSkary** [comment]
Ah right, i have forgot that i can save directly the entity.
Seems resonabe thanks.

**Comment by dj-nitehawk** [comment]
also a couple of other pointers.
1. when posting code, use following markdown
    \```csharp
    some code here
    \```
   
 2. instead of posting image of data, simply copy paste json after clicking on the `{}` view button in compass in a code block like so:
    \```
    some json here
    \```

**Comment by ItSkary** [comment]
Ok thanks for tips, i'll keep in mind for future post
