### ISSUE TITLE
Creating Text index with Language parameter

### ISSUE THREAD

**Issue by ozkanonur** [dj-nitehawk/MongoDB.Entities#96]
How do we create a text index with giving default_language parameter?
[Usage on mongo level](https://docs.mongodb.com/manual/tutorial/specify-language-for-text-index/)

**Comment by dj-nitehawk** [comment]
it's in the options
```csharp
await DB.Index<Person>()
        .Key(p => p.Name, KeyType.Text)
        .Option(o => o.DefaultLanguage = "en_US")
        .CreateAsync();
```

**Comment by ozkanonur** [comment]
Did work with .Option(o => o.DefaultLanguage = "turkish") instead of .Option(o => o.DefaultLanguage = "tr_TR")
