### ISSUE TITLE
Is there any plan to support `DB` with instance implemention?

### ISSUE THREAD

**Issue by snys98** [dj-nitehawk/MongoDB.Entities#97]
First, thanks for your efforts on this nice library.

Well, this issue is actually about two pain points during my usage of this library.
1. I'm looking for ways to implement an api with `UnitOfWork` pattern , and one of my idea is to attach an `IClientSession` to a **request scoped** `DB` instance(some concept like dbcontext in EF, but not static). Then all entity that query out of this `DB`(or dbcontext) will auto attach to this session, which will be auto-assigned to the `Entity.SaveAsync("session")` during the whole request scope.
2. I'm looking for someways to **extends** the `DB` class(eg. inheritance or extension methods), to get my custom collection or somewhat. But current implemention of static class won't do...

Thanks again, this has already been a good library. Forgive me if I'm asking for too much. :)

**Comment by dj-nitehawk** [comment]
thanks for the feedback...
there's no immediate plans for a UOW implementation as it's really not needed because the following achieves the same thing i believe:
```csharp
using var dbContext = new Transaction();

var author = new Author { Name = "test author" };
await dbContext.SaveAsync(author);

var book = new Book { Title = "test book", Author = author };
await dbContext.SaveAsync(book);

var authorName = await dbContext
    .Find<Author, string>()
    .MatchID(author.ID)
    .Project(a => a.Name)
    .ExecuteSingleAsync();

await dbContext
    .Update<Book>()
    .MatchID(book.ID)
    .Modify(b => b.Title, $"book by {authorName}")
    .ExecuteAsync();

await dbContext.CommitAsync();
```

for your second question, could you pls explain what you mean by `to get my custom collection`?

**Comment by snys98** [comment]
Wow, thanks. Maybe this `Transaction` is just something I'm looking for! And it would be really nice if query result entities can auto attach to it's source session, so we can use instance method like `book.SaveAsync()` to reuse session?
And `my custom collection` means some class that I write and implements `IMongoCollection`. It's has some **overrided** methods. Take `Find` as an example, I'd like it to filter out **SoftDeleted** items, and just like I write above, attach sessions to these entities. If `DB` is an class instance, then I can override or simpply extends a method like `GetMyCollection` to achieve it.

**Comment by dj-nitehawk** [comment]
okaaay... you can now do the following with v20.7.0-beta1
```csharp
public class BaseEntity : Entity
{
    public bool IsDeleted { get; set; }
}

public class Book : BaseEntity
{
    public string Title { get; set; }
}

public class MongoDbContext : DBContext
{
    public override Find<T> Find<T>()
    {
        return (Find<T>)base.Find<T>()
            .Match(b => b.Ne(nameof(BaseEntity.IsDeleted), true));
    }

    public override Find<T, TProjection> Find<T, TProjection>()
    {
        return base.Find<T, TProjection>()
            .Match(b => b.Ne(nameof(BaseEntity.IsDeleted), true));
    }
}
```
```csharp
var dbContext = new MongoDbContext();

await dbContext.SaveAsync(new[]
{
    new Book { Title = "first" },
    new Book { Title = "second" }
});

await dbContext
    .Update<Book>()
    .Match(b => b.Title == "second")
    .Modify(b => b.IsDeleted, true)
    .ExecuteAsync();

var activeBooks = await dbContext
    .Find<Book>()
    .ExecuteAsync();
```
you can do the same for transactions by simply inheriting from `Transaction` instead of `DBContext` like so:
```csharp
public class MongoDbContext : Transaction 
{
  ...
}
```

give the beta version a try and let me know your feedback.

as for auto attaching entities to sessions, i will need to look more deeply into how it can be achieved.

**Comment by dj-nitehawk** [comment]
v20.7 released with DBContext instance support. closing issue. pls reopen if need be.
