### ISSUE TITLE
'Please save the entity before performing this operation!'

### ISSUE THREAD

**Issue by kingsanu-production** [dj-nitehawk/MongoDB.Entities#99]
new RecruiterTable { Email = Email, Password = Password }
                .SavePreservingAsync(x=>new { x.Email, x.Password, x.ID});

this statement throw error

**Comment by dj-nitehawk** [comment]
`SavePreservingAsync` is used to update an already existing entity. it cannot do it's job if you exclude the `ID` property.
what exactly are you trying to do? to save a brand new entity or update an existing one?

**Comment by kingsanu-production** [comment]
I've a model of recruiter which have 100 fields, and on signup time only email & password i want to store, after next page only address will store, after another page only phone want to store. So with help of SaveAsync() it store all unusfull field into database when new record i going to store. so i want something where few field only store into database from recruiter model.

**Comment by dj-nitehawk** [comment]
if you don't want unused fields stored, you gotta use `[BsonIgnoreIfDefault]` attribute on your class properties.
```csharp
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Entities;
using System.Threading.Tasks;

namespace TestApplication
{
    public class Recruiter : Entity
    {
        public string Email { get; set; }
        public string Password { get; set; }
        [BsonIgnoreIfDefault] public string Address { get; set; }
        [BsonIgnoreIfDefault] public string Phone { get; set; }
    }

    public static class Program
    {
        private static async Task Main()
        {
            await DB.InitAsync("test");

            //step 1: create entity

            var recruiter = new Recruiter
            {
                Email = "info@info.info",
                Password = "123"
            };
            await recruiter.SaveAsync();

            //step 2: update address

            await DB.Update<Recruiter>()
                    .MatchID(recruiter.ID)
                    .Modify(r => r.Address, "123 street address")
                    .ExecuteAsync();

            //step 3: update phone

            await DB.Update<Recruiter>()
                    .MatchID(recruiter.ID)
                    .Modify(r => r.Phone, "12345")
                    .ExecuteAsync();
        }
    }
}
```

**Comment by kingsanu-production** [comment]
Thank you so much and big thanks my man from a real small bro heart. 
But it become hard work for the developer when there is 200 model to do it for each model and another developer are don't know which property to make [BsonIgnoreIfDefault]. sometimes when new record store we need at least one or two data to save.

IF something like 
new RecruiterTable { Email = Email, Password = Password }
.SavePreservingAsync(x=>new { x.Email, x.Password, x.ID});
should be there to help us to save only few property which developer want.

Thanks in advance from this brother.

**Comment by dj-nitehawk** [comment]
please give v20.7.0-beta2 a try from nuget. you can now do the following:
```csharp
await recruiter.SaveAsync(x => new { x.Email, x.Password })
```
note: if the entity being saved has no ID value, a new entity will be created. if there's a value for ID, then the specified properties will be updated in the db.

**Comment by dj-nitehawk** [comment]
api has changed in `v20.7.0-beta4`
```csharp
await recruiter.SaveOnlyAsync(x => new { x.Email, x.Password }) // will only save these two properties
await recruiter.SaveExceptAsync(x => new { x.Address }) // will save all other properties except address
```

**Comment by dj-nitehawk** [comment]
v20.7 has been released with [nailed down api](https://mongodb-entities.com/wiki/Entities-Save.html#save-entities-partially). closing issue. pls reopen if needed.
